// contracts/tools/generate.mjs
//
// Generates the Go binding of the event envelope from contracts/event-envelope.schema.json, and
// copies the schema next to it so the Go package can embed it. The schema is the only source of
// field names; this file contains no contract knowledge of its own beyond how to render it.
//
//   node contracts/tools/generate.mjs           write the generated files
//   node contracts/tools/generate.mjs --check   fail (exit 1) if the committed files differ

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { SCHEMA_REL_PATH, SHAPE_UNION_NAME, goPascal, loadModel } from "./schema-model.mjs";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const CONTRACTS_DIR = path.resolve(HERE, "..");
export const REPO_ROOT = path.resolve(CONTRACTS_DIR, "..");

export const GO_REL = "contracts/generated/go/envelope/envelope.go";
export const SCHEMA_COPY_REL = "contracts/generated/go/envelope/event-envelope.schema.json";

const GENERATED_BY = "contracts/tools/generate.mjs";
const REGENERATE = "node contracts/tools/generate.mjs";
const VERIFY = "node --test contracts/tools/";

// ---------------------------------------------------------------------------------------
// small text helpers
// ---------------------------------------------------------------------------------------

function wrap(text, width = 96) {
  const words = String(text ?? "").split(" ").filter(Boolean);
  const lines = [];
  let line = "";
  for (const word of words) {
    if (line.length === 0) line = word;
    else if (line.length + 1 + word.length <= width) line += ` ${word}`;
    else {
      lines.push(line);
      line = word;
    }
  }
  if (line.length > 0) lines.push(line);
  return lines.length > 0 ? lines : [""];
}

function goComment(text, indent = "") {
  const lines = Array.isArray(text) ? text : wrap(text);
  return lines.map((line) => (line.length > 0 ? `${indent}// ${line}` : `${indent}//`));
}

/** Pads every column except the last to the widest cell in that column plus one space. */
function alignRows(rows) {
  const widths = [];
  for (const row of rows) {
    row.forEach((cell, index) => {
      widths[index] = Math.max(widths[index] ?? 0, cell.length);
    });
  }
  return rows.map((row) => row.map((cell, index) => (index === row.length - 1 ? cell : cell.padEnd(widths[index] + 1))).join(""));
}

/**
 * Renders struct fields the way gofmt does: a comment line ends the alignment run that
 * precedes it and the field it documents opens the next run. Fields in one run are padded
 * to that run's widest cell in each column.
 * entries: [{ comments: string[] | null, name, type, tag }]
 */
function renderStructFields(entries, indent = "\t") {
  const out = [];
  let run = [];
  const flush = () => {
    if (run.length === 0) return;
    out.push(...alignRows(run.map((entry) => [`${indent}${entry.name}`, entry.type, entry.tag])));
    run = [];
  };
  for (const entry of entries) {
    if (entry.comments && entry.comments.length > 0) {
      flush();
      out.push(...entry.comments);
    }
    run.push(entry);
  }
  flush();
  return out;
}

/** English plural for the generated registry names: DetectionBasis -> DetectionBases. */
function pluralize(name) {
  return /is$/.test(name) ? name.replace(/is$/, "es") : `${name}s`;
}

function enumConstName(typeName, value) {
  return `${typeName}${goPascal(value)}`;
}

// ---------------------------------------------------------------------------------------
// Go types
// ---------------------------------------------------------------------------------------

const GO_FORMAT_TYPES = { uuid: "UUID", "date-time": "DateTime" };

function goTypeName(field) {
  if (field.type === "string") {
    if (field.typeName) return field.typeName;
    if (field.enumType) return field.enumType;
    if (field.format && GO_FORMAT_TYPES[field.format]) return GO_FORMAT_TYPES[field.format];
    return "string";
  }
  if (field.type === "integer") return "int64";
  if (field.type === "number") return "float64";
  if (field.type === "boolean") return "bool";
  if (field.type === "object") return field.objectType;
  if (field.type === "array") return `[]${field.itemsType}`;
  throw new Error(`generate: no Go type for ${field.owner}.${field.name}`);
}

function goType(field, required) {
  const base = goTypeName(field);
  return required ? base : `*${base}`;
}

// ---------------------------------------------------------------------------------------
// rendering
// ---------------------------------------------------------------------------------------

function renderHeader(model) {
  const lines = [
    `// Code generated by ${GENERATED_BY} from ${SCHEMA_REL_PATH}. DO NOT EDIT.`,
    `// Regenerate: ${REGENERATE}    Drift is a test failure: ${VERIFY}`,
    "//",
    ...wrap(`Contract: ${model.title}. ${model.description}`, 100).map((l) => `// ${l}`),
    "//",
    `// Source of truth: ${model.schemaId}`,
    "//",
    "// Encoding of the contract in Go:",
    "//   - a field the schema requires is a value field with no `omitempty`; a field the schema",
    "//     permits but does not require is a pointer with `omitempty` (an array is a",
    "//     pointer-to-slice so that present-but-empty survives a round trip); a field the schema",
    "//     forbids for a kind and mode is absent from that variant's struct.",
    "//   - DeviceSubmission is a closed union, one implementation per variant, each asserted at",
    "//     compile time. DecodeDeviceSubmission dispatches on kind and collection_mode, refuses an",
    "//     unknown kind or mode, and refuses a field the variant does not declare. It does not",
    "//     check the schema's value constraints: validate a record against Schema first.",
  ];
  const permitted = model.variants
    .map((v) => (v.optional.length > 0 ? `${v.name}: ${v.optional.join(", ")}` : null))
    .filter(Boolean);
  if (permitted.length > 0) {
    lines.push("//");
    lines.push("// Permitted by the schema but not required, so optional in the structs below:");
    for (const entry of permitted) lines.push(`//   ${entry}`);
  }
  for (const warning of model.audit.branchWarnings) {
    lines.push("//");
    lines.push(`// SCHEMA NOTE: ${warning}`);
  }
  return lines;
}

function renderEnum(enumDef) {
  const out = [];
  out.push(...goComment(`${enumDef.typeName} is the closed set from ${enumDef.source}. ${enumDef.description}`));
  out.push(`type ${enumDef.typeName} string`);
  out.push("");
  out.push("const (");
  out.push(
    ...alignRows(enumDef.values.map((value) => [`\t${enumConstName(enumDef.typeName, value)}`, `${enumDef.typeName} = ${JSON.stringify(value)}`])),
  );
  out.push(")");
  out.push("");
  out.push(...goComment("Valid reports whether the value is inside the closed set."));
  out.push(`func (v ${enumDef.typeName}) Valid() bool {`);
  out.push("\tswitch v {");
  out.push(`\tcase ${enumDef.values.map((value) => enumConstName(enumDef.typeName, value)).join(", ")}:`);
  out.push("\t\treturn true");
  out.push("\t}");
  out.push("\treturn false");
  out.push("}");
  out.push("");
  out.push(...goComment(`All${pluralize(enumDef.typeName)} returns the closed set in schema order.`));
  out.push(`func All${pluralize(enumDef.typeName)}() []${enumDef.typeName} {`);
  out.push(`\treturn []${enumDef.typeName}{${enumDef.values.map((value) => enumConstName(enumDef.typeName, value)).join(", ")}}`);
  out.push("}");
  out.push("");
  return out;
}

function renderObject(objectDef) {
  const out = [];
  out.push(...goComment(`${objectDef.typeName}: ${objectDef.description}`));
  out.push(`type ${objectDef.typeName} struct {`);
  out.push(
    ...renderStructFields(
      objectDef.fields.map((field) => {
        const required = objectDef.required.includes(field.name);
        return {
          comments: field.description ? goComment(field.description, "\t") : null,
          name: goPascal(field.name),
          type: goType(field, required),
          tag: `\`json:"${field.name}${required ? "" : ",omitempty"}"\``,
        };
      }),
    ),
  );
  out.push("}");
  out.push("");
  return out;
}

function renderCore(model) {
  const out = [];
  out.push(...goComment("EnvelopeCore holds the fields required on every envelope, whatever its kind. Each variant"));
  out.push(...goComment("embeds it and adds its own fields."));
  out.push("type EnvelopeCore struct {");
  out.push(
    ...renderStructFields(
      model.coreFields.map((field) => ({
        comments: field.description ? goComment(field.description, "\t") : null,
        name: goPascal(field.name),
        type: goType(field, true),
        tag: `\`json:"${field.name}"\``,
      })),
    ),
  );
  out.push("}");
  out.push("");
  return out;
}

function renderVariant(variant) {
  const out = [];
  const where = variant.mode ? ` at collection mode ${JSON.stringify(variant.mode)}` : "";
  const requiredOwn = variant.ownFields.filter((f) => f.required).map((f) => f.name);
  out.push(...goComment(`${variant.name} is what a device sends for kind ${JSON.stringify(variant.kind)}${where}.`));
  out.push("//");
  out.push(...goComment(`Required: the common core${variant.narrowedCore.length > 0 ? ` (${variant.narrowedCore.map((f) => f.name).join(", ")} pinned)` : ""}${requiredOwn.length > 0 ? `, plus ${requiredOwn.join(", ")}` : ""}.`));
  out.push(...goComment(variant.optional.length > 0 ? `Permitted but not required: ${variant.optional.join(", ")}.` : "Permitted but not required: nothing beyond the required fields."));
  out.push(...goComment(variant.forbidden.length > 0 ? `Must not carry, so absent from this struct: ${variant.forbidden.join(", ")}.` : "No field is forbidden for this kind."));
  out.push(`type ${variant.name} struct {`);
  out.push("\tEnvelopeCore");
  if (variant.ownFields.length > 0) {
    out.push("");
    out.push(
      ...renderStructFields(
        variant.ownFields.map((field) => ({
          comments: null,
          name: goPascal(field.name),
          type: goType(field, field.required),
          tag: `\`json:"${field.name}${field.required ? "" : ",omitempty"}"\``,
        })),
      ),
    );
  }
  out.push("}");
  out.push("");
  out.push(...goComment(`deviceSubmission marks ${variant.name} as a member of the closed ${SHAPE_UNION_NAME.device} union.`));
  out.push(`func (*${variant.name}) deviceSubmission() {}`);
  out.push("");
  out.push(...goComment("Core returns the common core of the envelope."));
  out.push(`func (e *${variant.name}) Core() EnvelopeCore { return e.EnvelopeCore }`);
  out.push("");
  return out;
}

function renderUnionAndDecoder(model) {
  const out = [];
  const unionName = SHAPE_UNION_NAME.device;
  out.push(...goComment(`${unionName} is the closed union of what a device is permitted to send: one implementation per kind and, for prompts, per collection mode. Every member omits \`received_at\`, which the server assigns.`));
  out.push(`type ${unionName} interface {`);
  out.push("\tdeviceSubmission()");
  out.push("\tCore() EnvelopeCore");
  out.push("}");
  out.push("");
  out.push(...goComment(`Compile-time proof that every variant belongs to ${unionName}.`));
  for (const variant of model.variants) out.push(`var _ ${unionName} = (*${variant.name})(nil)`);
  out.push("");

  out.push(...goComment("kindProbe reads only the discriminators, so dispatch never guesses a shape."));
  out.push("type kindProbe struct {");
  out.push(
    ...alignRows([
      ["\tKind", "Kind", "`json:\"kind\"`"],
      ["\tCollectionMode", "CollectionMode", "`json:\"collection_mode\"`"],
    ]),
  );
  out.push("}");
  out.push("");
  out.push(...goComment("decodeInto decodes data into one variant, refusing a field the variant does not declare."));
  out.push(`func decodeInto(data []byte, dst ${unionName}) (${unionName}, error) {`);
  out.push("\tdecoder := json.NewDecoder(bytes.NewReader(data))");
  out.push("\tdecoder.DisallowUnknownFields()");
  out.push("\tif err := decoder.Decode(dst); err != nil {");
  out.push('\t\treturn nil, fmt.Errorf("envelope: %T: %w", dst, err)');
  out.push("\t}");
  out.push("\treturn dst, nil");
  out.push("}");
  out.push("");

  const fnName = `Decode${unionName}`;
  out.push(
    ...goComment(
      `${fnName} decodes a device submission and returns the variant selected by kind, and for prompts by collection_mode. It refuses an unknown kind, an unknown mode, and a field the variant does not declare.`,
    ),
  );
  out.push(`func ${fnName}(data []byte) (${unionName}, error) {`);
  out.push("\tvar probe kindProbe");
  out.push("\tif err := json.Unmarshal(data, &probe); err != nil {");
  out.push('\t\treturn nil, fmt.Errorf("envelope: device submission is not a JSON object: %w", err)');
  out.push("\t}");
  out.push("\tswitch probe.Kind {");
  for (const kind of model.kinds) {
    const members = model.variants.filter((v) => v.kind === kind);
    out.push(`\tcase ${enumConstName("Kind", kind)}:`);
    if (members.some((v) => v.mode !== null)) {
      out.push("\t\tswitch probe.CollectionMode {");
      for (const variant of members.filter((v) => v.mode !== null)) {
        out.push(`\t\tcase ${enumConstName("CollectionMode", variant.mode)}:`);
        out.push(`\t\t\treturn decodeInto(data, &${variant.name}{})`);
      }
      out.push("\t\tdefault:");
      out.push(`\t\t\treturn nil, fmt.Errorf("envelope: collection_mode %q is outside the closed set %v for kind %q", probe.CollectionMode, AllCollectionModes(), probe.Kind)`);
      out.push("\t\t}");
    } else {
      out.push(`\t\treturn decodeInto(data, &${members[0].name}{})`);
    }
  }
  out.push("\tdefault:");
  out.push(`\t\treturn nil, fmt.Errorf("envelope: kind %q is outside the closed registry %v", probe.Kind, AllKinds())`);
  out.push("\t}");
  out.push("}");
  out.push("");
  return out;
}

function renderGo(model) {
  const out = [...renderHeader(model), ""];
  out.push("// Package envelope is the Go binding of the event envelope contract.");
  out.push("package envelope");
  out.push("");
  out.push("import (");
  out.push('\t"bytes"');
  out.push('\t_ "embed"');
  out.push('\t"encoding/json"');
  out.push('\t"fmt"');
  out.push(")");
  out.push("");
  out.push(...goComment("Schema is the contract document these types were generated from, byte for byte."));
  out.push("//");
  out.push(`//go:embed ${path.posix.basename(SCHEMA_COPY_REL)}`);
  out.push("var Schema string");
  out.push("");
  out.push(...goComment("SchemaID is the $id of Schema."));
  out.push(`const SchemaID = ${JSON.stringify(model.schemaId)}`);
  out.push("");
  out.push(...goComment("SchemaVersion is the only schema_version this contract describes; a new value is a new contract."));
  out.push(`const SchemaVersion = ${JSON.stringify(model.schemaVersion)}`);
  out.push("");
  out.push(...goComment("Wire-level string aliases. They are aliases, not defined types, so a value from the"));
  out.push(...goComment("wire can be used without conversion; they exist to name the format in signatures."));
  out.push("type Sha256 = string");
  out.push("");
  out.push("type UUID = string");
  out.push("");
  out.push("type DateTime = string");
  out.push("");

  for (const enumDef of model.enums) out.push(...renderEnum(enumDef));
  for (const objectDef of model.objects) out.push(...renderObject(objectDef));
  out.push(...renderCore(model));
  for (const variant of model.variants) out.push(...renderVariant(variant));
  out.push(...renderUnionAndDecoder(model));

  return `${out.join("\n").trimEnd()}\n`;
}

// ---------------------------------------------------------------------------------------
// generation and CLI
// ---------------------------------------------------------------------------------------

export function renderAll({ contractsDir = CONTRACTS_DIR } = {}) {
  const schemaPath = path.join(contractsDir, "event-envelope.schema.json");
  const model = loadModel(schemaPath);
  return [
    { rel: GO_REL, content: renderGo(model) },
    { rel: SCHEMA_COPY_REL, content: readFileSync(schemaPath, "utf8") },
  ];
}

function normalize(text) {
  return text.replace(/\r\n/g, "\n");
}

function firstDifference(committed, generated) {
  const a = normalize(committed).split("\n");
  const b = normalize(generated).split("\n");
  const limit = Math.max(a.length, b.length);
  for (let i = 0; i < limit; i += 1) {
    if (a[i] !== b[i]) {
      return { line: i + 1, committed: a[i] ?? "<end of file>", generated: b[i] ?? "<end of file>" };
    }
  }
  return null;
}

export function checkGenerated({ repoRoot = REPO_ROOT, contractsDir = CONTRACTS_DIR } = {}) {
  const problems = [];
  for (const { rel, content } of renderAll({ contractsDir })) {
    const absolute = path.join(repoRoot, rel);
    if (!existsSync(absolute)) {
      problems.push(`${rel}: is missing; run \`${REGENERATE}\``);
      continue;
    }
    const committed = readFileSync(absolute, "utf8");
    if (normalize(committed) === normalize(content)) continue;
    const difference = firstDifference(committed, content);
    problems.push(
      `${rel}: differs from a fresh generation of ${SCHEMA_REL_PATH} (first difference at line ${difference.line})\n` +
        `    committed: ${difference.committed}\n` +
        `    generated: ${difference.generated}`,
    );
  }
  return problems;
}

export function writeGenerated({ repoRoot = REPO_ROOT, contractsDir = CONTRACTS_DIR } = {}) {
  const written = [];
  for (const { rel, content } of renderAll({ contractsDir })) {
    const absolute = path.join(repoRoot, rel);
    mkdirSync(path.dirname(absolute), { recursive: true });
    writeFileSync(absolute, content, "utf8");
    written.push(rel);
  }
  return written;
}

function main(argv) {
  const unknown = argv.filter((arg) => arg !== "--check");
  if (unknown.length > 0) {
    process.stderr.write(`generate.mjs: unknown argument(s): ${unknown.join(", ")}\nusage: node ${GENERATED_BY} [--check]\n`);
    return 2;
  }
  if (argv.includes("--check")) {
    const problems = checkGenerated();
    if (problems.length > 0) {
      process.stderr.write(`generate.mjs --check: the committed generated files are not what ${SCHEMA_REL_PATH} produces\n`);
      for (const problem of problems) process.stderr.write(`  ${problem}\n`);
      process.stderr.write(`run: ${REGENERATE}\n`);
      return 1;
    }
    process.stdout.write(`generate.mjs --check: the generated files match ${SCHEMA_REL_PATH}\n`);
    return 0;
  }
  for (const rel of writeGenerated()) {
    process.stdout.write(`generate.mjs: wrote ${rel}\n`);
  }
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exitCode = main(process.argv.slice(2));
}
