/**
 * Project Cockpit — client bundle builder.
 *
 * The host serves a plugin's client half as a single lazy-CJS file, so this
 * script concatenates the ESM sources into one `window.__ModuleLoader__.load`
 * wrapper. Doing it here rather than shipping a bundler keeps the build to one
 * dependency-free step that works on any Node the user already has.
 *
 * Import statements are rewritten to the bundle's own `require(...)`, which
 * resolves React from the shell's frozen platform module table. No module here
 * may import anything else — `--check` enforces that.
 *
 * Run: node .cockpit/tools/build-client.mjs [--check]
 */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const here = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(here, '..')

/** The package name the shell registers this bundle under. */
const PACKAGE = 'dsh-project-cockpit'

/** Modules the shell's platform table can answer, and nothing else. */
const ALLOWED_EXTERNAL = new Set(['react', 'react-dom', 'react/jsx-runtime'])

/** Source order matters: later files may use earlier declarations. */
const SOURCES = ['lib/client/styles.js', 'lib/client/viewmodel.js', 'lib/client/index.js']

/**
 * Rewrite one ESM source into bundle body text.
 * @param file workspace-relative source path.
 * @param code the file's text.
 * @returns transformed code.
 */
function transform(file, code) {
  let out = code
  const imports = []
  out = out.replace(/^import\s+([\s\S]*?)\s+from\s+'([^']+)'\s*$/gmu, (match, clause, specifier) => {
    // Relative imports are between this package's own modules, which are all
    // inlined into one bundle — they vanish rather than resolve.
    if (specifier.startsWith('.')) return `/* inlined ${specifier} */`
    if (!ALLOWED_EXTERNAL.has(specifier)) {
      throw new Error(`${file}: import of ${JSON.stringify(specifier)} is not in the shell's platform module table`)
    }
    const binding = clause.trim()
    if (binding.startsWith('* as ')) {
      imports.push(`var ${binding.slice(5).trim()} = require(${JSON.stringify(specifier)});`)
    } else if (binding.startsWith('{')) {
      imports.push(`var { ${binding.slice(1, -1).trim()} } = require(${JSON.stringify(specifier)});`)
    } else {
      imports.push(`var ${binding} = require(${JSON.stringify(specifier)});`)
    }
    return `/* import ${specifier} */`
  })
  if (/^import\s/mu.test(out)) {
    throw new Error(`${file}: an import survived rewriting — the bundle would silently lose a module`)
  }
  // Exports become plain declarations; the bundle's export set is author-owned below.
  out = out.replace(/^export\s+(const|let|var|function|class)\s/gmu, '$1 ')
  if (/^export\s/mu.test(out)) {
    throw new Error(`${file}: an export survived rewriting; only the entry file may export, via the author-owned epilogue`)
  }
  return `${imports.join('\n')}\n${out}`.trim()
}

/** Build the bundle text. */
function build() {
  const parts = []
  for (const relative of SOURCES) {
    const absolute = path.join(root, relative)
    if (!existsSync(absolute)) throw new Error(`missing source ${relative}`)
    const code = readFileSync(absolute, 'utf8')
    parts.push(`// ---- ${relative} ----\n${transform(relative, code)}`)
  }

  const body = parts.join('\n\n')

  return `/* dsh-project-cockpit — client bundle. Generated by .cockpit/tools/build-client.mjs; edit .cockpit/lib/client/*.js instead. */
window.__ModuleLoader__.load({
\tid: ${JSON.stringify(PACKAGE)},
\tfactory: (require) => {
\t\tvar module = { exports: {} };
\t\tvar exports = module.exports;
\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

${body.replace(/^/gmu, '\t\t')}

\t\texports.apply = apply;
\t\texports.inject = inject;
\t\texports.name = name;
\t\treturn module.exports;
\t}
});
`
}

const target = path.join(root, 'lib', 'client.js')
const bundle = build()

if (process.argv.includes('--check')) {
  const existing = existsSync(target) ? readFileSync(target, 'utf8') : ''
  if (existing !== bundle) {
    process.stderr.write('client bundle is stale — run node .cockpit/tools/build-client.mjs\n')
    process.exitCode = 1
  } else {
    process.stdout.write(`client bundle is current (${bundle.length} bytes)\n`)
  }
} else {
  mkdirSync(path.dirname(target), { recursive: true })
  writeFileSync(target, bundle)
  process.stdout.write(`wrote ${path.relative(root, target)} (${bundle.length} bytes)\n`)
}
