// build-index.mjs — inline the module graph into apps/dashboard/index.html.
//
// WHY THIS EXISTS. Browsers refuse an external ES module fetch from a `file://` page: the module
// request is cross-origin from origin `null`, so `<script type="module" src="./src/app.js">` fails
// in every mainstream browser when the page is opened straight off disk. The requirement is that a
// human can open the dashboard and see every state, so index.html carries the whole graph in one
// inline module block: an inline module performs no fetch, and `file://` loading works.
//
// This is not a build step for the application. `src/*.js` are the source of truth and are what the
// tests import; index.html is a *snapshot* of them, and `test/index-html.test.mjs` regenerates it
// and fails if it has drifted. Anyone editing src/ runs `node tools/build-index.mjs` and commits
// both, exactly as they would for any generated artefact with a drift gate.
//
//   node tools/build-index.mjs            # regenerate index.html
//   node tools/build-index.mjs --check    # fail if index.html is stale

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
export const INDEX_PATH = join(ROOT, 'index.html');
const TEMPLATE_PATH = join(HERE, 'index.template.html');

/** Dependency order. A module may only reference names declared earlier in this list. */
export const MODULE_ORDER = Object.freeze([
  'vocab.js',
  'format.js',
  'states.js',
  'dsl.js',
  'transport.js',
  'fixtures.js',
  'scenarios.js',
  'questions.js',
  'views.js',
  'unavailable.js',
  'render.js',
  'app.js',
]);

/** Names the epilogue exports, so a test can import the inline module and drive it. */
const PUBLIC_NAMES = Object.freeze([
  'boot', 'createDashboard', 'parseHash', 'SCREENS', 'SCREEN_IDS',
  'readState', 'measureOf', 'isSuppressed', 'sumMeasure', 'renderScreen', 'renderValue',
  'createQueryApi', 'createStubTransport', 'scenarioTransport', 'SCENARIO_NAMES',
  'QUESTIONS', 'buildDocument', 'buildTemplate', 'GAPS',
]);

/** Strip the module syntax and return the body, plus the top-level names it declares. */
function stripModule(source, name) {
  let body = source;
  // import statements, single- or multi-line
  body = body.replace(/^import\s[\s\S]*?from\s*'[^']*';\s*$/gm, '');
  // `export { a, b };` re-export blocks
  body = body.replace(/^export\s*\{[\s\S]*?\};\s*$/gm, '');
  // `export default` is not used anywhere in this package, and would not survive concatenation
  if (/^export\s+default\b/m.test(body)) {
    throw new Error(`${name}: export default cannot be inlined; use a named export.`);
  }
  // the `export` keyword on declarations
  body = body.replace(/^export\s+(?=(const|let|var|function|class|async)\b)/gm, '');
  if (/^\s*import\s/m.test(body)) throw new Error(`${name}: an import survived stripping.`);
  if (/^export\s/m.test(body)) throw new Error(`${name}: an export survived stripping.`);

  const names = new Set();
  for (const m of body.matchAll(/^(?:const|let|var|function|class|async function)\s+([A-Za-z_$][\w$]*)/gm)) names.add(m[1]);
  return { body, names: [...names] };
}

/** The inlined module body. Throws on a name collision, because concatenation has no scopes. */
export function buildInlineModule() {
  const seen = new Map();
  const parts = [];
  for (const name of MODULE_ORDER) {
    const path = join(ROOT, 'src', name);
    if (!existsSync(path)) throw new Error(`src/${name} is missing.`);
    const { body, names } = stripModule(readFileSync(path, 'utf8'), name);
    for (const declared of names) {
      if (seen.has(declared)) {
        throw new Error(`top-level name collision: "${declared}" is declared in both ${seen.get(declared)} and ${name}. Rename one before inlining.`);
      }
      seen.set(declared, name);
    }
    parts.push(`// ─── src/${name} ${'─'.repeat(Math.max(0, 62 - name.length))}\n${body.trim()}\n`);
  }
  const missing = PUBLIC_NAMES.filter((n) => !seen.has(n));
  if (missing.length > 0) throw new Error(`the epilogue exports names no module declares: ${missing.join(', ')}`);

  return [
    '// GENERATED by tools/build-index.mjs — edit src/*.js and regenerate. Drift is a test failure.',
    '// One inline module, so this page opens from the filesystem: a browser refuses an external',
    '// module fetch from file://, and an inline module fetches nothing.',
    '',
    ...parts,
    '// ─── epilogue ─────────────────────────────────────────────────────────────────',
    'let __booted = false;',
    'function __boot() {',
    '  if (__booted) return;',
    '  __booted = true;',
    "  boot({ document, scenario: 'realistic' });",
    '}',
    "if (typeof document !== 'undefined') {",
    "  if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', __boot);",
    '  else __boot();',
    '}',
    '',
    `export { ${PUBLIC_NAMES.join(', ')} };`,
    '',
  ].join('\n');
}

export function buildIndexHtml() {
  const template = readFileSync(TEMPLATE_PATH, 'utf8');
  const marker = '<!--__INLINE_MODULE__-->';
  if (!template.includes(marker)) throw new Error('tools/index.template.html has no <!--__INLINE_MODULE__--> marker.');
  const script = `<script type="module">\n${buildInlineModule()}</script>`;
  return template.replace(marker, script);
}

const invokedDirectly = process.argv[1]?.endsWith('build-index.mjs') ?? false;
if (invokedDirectly) {
  const html = buildIndexHtml();
  if (process.argv.includes('--check')) {
    const current = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, 'utf8').replace(/\r\n/g, '\n') : '';
    if (current !== html) {
      console.error('index.html is stale: run `node tools/build-index.mjs` from apps/dashboard.');
      process.exit(1);
    }
    console.log(`index.html is in sync (${html.length} bytes, ${MODULE_ORDER.length} modules inlined)`);
    process.exit(0);
  }
  writeFileSync(INDEX_PATH, html);
  console.log(`wrote index.html (${html.length} bytes, ${MODULE_ORDER.length} modules inlined)`);
}
