#!/usr/bin/env node
// device/installer/render.mjs - generate the platform service definitions from device/installer/manifest.mjs.
//
//   node device/installer/render.mjs           # (re)write device/installer/generated/**
//   node device/installer/render.mjs --check   # exit 1 if device/installer/generated/** differs from the manifest
//   node device/installer/render.mjs --list    # print the configuration catalogue
//
// The generated files carry layout and placeholders only; the trust anchors and the version are
// release inputs that build.mjs applies to the stage.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { extensionId } from '../extension/tools/extension-id.mjs';
import { CONFIG, LAYOUT, NATIVE_HOST, PRODUCT, TENANT_PACKAGE, nativeHostManifest } from './manifest.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const GENERATED = join(ROOT, 'device', 'installer', 'generated');
const GENERATED_BY = 'generated by device/installer/render.mjs from device/installer/manifest.mjs; edit the manifest, not this file';
const HOST_FILE = `${NATIVE_HOST.name}.json`;

function tenantEnvExample() {
  const example = {
    SAC_TENANT_ID: '00000000-0000-0000-0000-000000000000',
    SAC_DEVICE_ENDPOINT: 'https://devices.example.com',
    SAC_DEPLOYMENT_KEY: '',
  };
  return [
    `# ${GENERATED_BY}`,
    `# ${TENANT_PACKAGE.fileName}: control-api writes one per deployment package download, beside the`,
    '# generic installer, and the installer copies it to tenant.env. The deployment key is a secret.',
    ...TENANT_PACKAGE.keys.map((k) => `${k}=${example[k]}`),
    '',
  ].join('\n');
}

function systemdUnit(L) {
  // The agent installs its interception root into the system trust store and writes the CLI shim's
  // files under the configuration directory and /etc/profile.d, so those locations are writable;
  // everything else outside its own state is read-only. The browser relay's socket is in
  // /run/shadow-ai-capture. The agent logs to standard error, which the journal collects.
  const writable = [L.statedir, L.configdir, '-/usr/local/share/ca-certificates', '-/etc/ssl/certs', '-/etc/pki/ca-trust', '-/etc/profile.d'];
  return [
    `# ${GENERATED_BY}`,
    '[Unit]',
    `Description=${PRODUCT.displayName} endpoint agent`,
    'After=network-online.target',
    'Wants=network-online.target',
    'StartLimitIntervalSec=60',
    'StartLimitBurst=5',
    '',
    '[Service]',
    'Type=simple',
    `ExecStart=${L.bindir}/capture-core --config-file ${L.configFile} --config-file ${L.tenantFile}`,
    'Restart=on-failure',
    'RestartSec=5',
    'NoNewPrivileges=true',
    'ProtectSystem=strict',
    'ProtectHome=true',
    'PrivateTmp=true',
    `ReadWritePaths=${writable.join(' ')}`,
    'RuntimeDirectory=shadow-ai-capture',
    'RuntimeDirectoryMode=0755',
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

function launchdPlist(L) {
  const args = [`${L.bindir}/capture-core`, '--config-file', L.configFile, '--config-file', L.tenantFile];
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    `<!-- ${GENERATED_BY} -->`,
    '<plist version="1.0">',
    '<dict>',
    '  <key>Label</key>',
    `  <string>${L.serviceName}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    ...args.map((a) => `    <string>${a}</string>`),
    '  </array>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <!-- Restart after a crash, not after a clean stop. -->',
    '  <key>KeepAlive</key>',
    '  <dict>',
    '    <key>SuccessfulExit</key>',
    '    <false/>',
    '  </dict>',
    '  <key>StandardOutPath</key>',
    `  <string>${L.logdir}/capture-core.out.log</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${L.logdir}/capture-core.err.log</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

function nativeHostJson(os) {
  return JSON.stringify(nativeHostManifest(os, extensionId()), null, 2) + '\n';
}

// Protected DACLs on the data folders, so nothing is inherited from ProgramData (which lets every user
// read). SYSTEM and Administrators have full control everywhere. profile\ (the deployment key) and
// state\ (the credential, the spool, held content) give no one else access. Users may list the root,
// not inherited, and read cli\, where the CLI shim writes the CA bundle and proxy script every
// user's tools load. 0x1200a9 is read and execute.
const ADMIN_ONLY = 'D:PAI(A;OICI;FA;;;SY)(A;OICI;FA;;;BA)';
export const DATA_FOLDER_ACL = {
  DATAFOLDER: `${ADMIN_ONLY}(A;;0x1200a9;;;BU)`,
  PROFILEFOLDER: ADMIN_ONLY,
  STATEFOLDER: ADMIN_ONLY,
  CLIFOLDER: `${ADMIN_ONLY}(A;OICI;0x1200a9;;;BU)`,
};

function wixSource() {
  const L = LAYOUT.windows;
  const tenantName = TENANT_PACKAGE.fileName;
  const profileName = (file) => file.slice(L.profiledir.length + 1);
  const config = profileName(L.configFile);
  const tenant = profileName(L.tenantFile);
  const reason =
    `${PRODUCT.displayName} needs ${tenantName} beside ShadowAICapture.msi: none was found there and this device ` +
    'has no tenant configuration installed. Download the deployment package from Settings, Deployment and ' +
    'run the MSI from the folder that holds both files.';
  const cmd = (args) => `&quot;[System64Folder]cmd.exe&quot; ${args}`;
  const checkTenant = cmd(
    `/d /c if exist &quot;[TENANTENV_DIR]${tenantName}&quot; (exit 0) else if exist &quot;[PROFILEFOLDER]${tenant}&quot; (exit 0) else (echo ${reason} &amp; exit 1)`,
  );
  const serviceArgs = `--config-file &quot;[PROFILEFOLDER]${config}&quot; --config-file &quot;[PROFILEFOLDER]${tenant}&quot;`;
  const dataFolder = (dir) => `        <CreateFolder Directory="${dir}"><PermissionEx Sddl="${DATA_FOLDER_ACL[dir]}" /></CreateFolder>`;
  const registryKey = (key) =>
    [
      `        <RegistryKey Root="HKLM" Key="${key}" ForceDeleteOnUninstall="yes">`,
      '          <RegistryValue Type="string" Value="[#Fil_NativeHost]" />',
      '        </RegistryKey>',
    ].join('\n');

  return `<?xml version="1.0" encoding="UTF-8"?>
<!-- ${GENERATED_BY} -->
<!--
  The generic Windows package: code only. The tenant file is not in the package; the MSI copies it at
  install from ${tenantName} in the folder it runs from, so one signed MSI serves every tenant
  and the install command takes no properties. ProductVersion and StageDir are build variables.
-->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Package Name="${PRODUCT.displayName}" Manufacturer="${PRODUCT.manufacturer}" Version="$(var.ProductVersion)"
           UpgradeCode="${PRODUCT.upgradeCode}" Scope="perMachine" Compressed="yes">
    <MajorUpgrade AllowSameVersionUpgrades="yes"
                  DowngradeErrorMessage="A newer version of ${PRODUCT.displayName} is already installed." />
    <MediaTemplate EmbedCab="yes" />
    <Property Id="ARPNOMODIFY" Value="1" />
    <Property Id="ARPNOREPAIR" Value="1" />

    <StandardDirectory Id="ProgramFiles64Folder">
      <Directory Id="INSTALLFOLDER" Name="ShadowAICapture">
        <Directory Id="BINFOLDER" Name="bin" />
        <Directory Id="CLASSIFIERFOLDER" Name="classifier" />
      </Directory>
    </StandardDirectory>
    <StandardDirectory Id="CommonAppDataFolder">
      <Directory Id="DATAFOLDER" Name="ShadowAICapture">
        <Directory Id="PROFILEFOLDER" Name="profile" />
        <Directory Id="STATEFOLDER" Name="state" />
        <Directory Id="CLIFOLDER" Name="cli" />
      </Directory>
    </StandardDirectory>

    <ComponentGroup Id="Product">
      <!-- The agent: a LocalSystem service that reads the vendor file, then the tenant file. -->
      <Component Id="Cmp_CaptureCore" Directory="BINFOLDER">
        <File Id="Fil_CaptureCore" Source="$(var.StageDir)\\bin\\capture-core.exe" KeyPath="yes" />
        <ServiceInstall Id="Svc" Name="${L.serviceName}" DisplayName="${PRODUCT.displayName}"
                        Description="Observes AI submissions on this device and sends them to the tenant."
                        Type="ownProcess" Start="auto" ErrorControl="normal" Account="LocalSystem"
                        Arguments="${serviceArgs}" />
        <ServiceControl Id="SvcControl" Name="${L.serviceName}" Stop="both" Remove="uninstall" Wait="yes" />
      </Component>
      <Component Id="Cmp_ClassifierHost" Directory="BINFOLDER">
        <File Id="Fil_ClassifierHost" Source="$(var.StageDir)\\bin\\classifier-host.exe" KeyPath="yes" />
      </Component>
      <!-- The browser extension's native messaging host, registered for Chrome and Edge. -->
      <Component Id="Cmp_NativeHost" Directory="BINFOLDER">
        <File Id="Fil_NativeHost" Source="$(var.StageDir)\\etc\\${HOST_FILE}" KeyPath="yes" />
${NATIVE_HOST.registryKeys.map(registryKey).join('\n')}
      </Component>
      <!-- profile and state hold the deployment key, the device credential and the spool: SYSTEM and
           Administrators only. Users may read cli. A component keyed by a folder needs a fixed GUID. -->
      <Component Id="Cmp_DataFolders" Directory="DATAFOLDER" Guid="5B0F5E53-2C0B-4B4B-9E3C-6D7C1C2F9A10">
${Object.keys(DATA_FOLDER_ACL).map(dataFolder).join('\n')}
      </Component>
      <!-- The vendor file, and the tenant file copied from the folder the MSI runs from. -->
      <Component Id="Cmp_VendorConfig" Directory="PROFILEFOLDER">
        <File Id="Fil_VendorConfig" Source="$(var.StageDir)\\etc\\${config}" KeyPath="yes" />
        <CopyFile Id="CopyTenantEnv" SourceProperty="TENANTENV_DIR" SourceName="${tenantName}"
                  DestinationDirectory="PROFILEFOLDER" DestinationName="${tenant}" />
      </Component>
      <Files Directory="CLASSIFIERFOLDER" Include="$(var.StageDir)\\classifier\\**" />
    </ComponentGroup>

    <!--
      The tenant file. ResolveSource sets SourceDir for a first install or a major upgrade only (at a
      removal it would prompt for the source). MoveFiles refuses SourceDir itself as a source folder,
      so it is copied into TENANTENV_DIR. A launch condition cannot test the source folder, so an
      immediate action after costing fails the install, before anything changes, when there is
      neither a tenant file beside the MSI nor one installed. MoveFiles replaces an installed
      tenant.env with a supplied one, and a copied file survives an upgrade.
    -->
    <SetProperty Id="TENANTENV_DIR" Value="[SourceDir]" After="ResolveSource" Sequence="execute" Condition="NOT Installed" />
    <CustomAction Id="CheckTenantConfig" Directory="CommonAppDataFolder" Execute="immediate" Return="check"
                  ExeCommand="${checkTenant}" />
    <!-- Started without waiting and without failing the install: a service that does not start stays
         registered for diagnosis instead of rolling the install back. Output goes to nul so sc.exe
         never waits on a console. -->
    <CustomAction Id="StartService" Directory="CommonAppDataFolder" Execute="deferred" Impersonate="no" Return="asyncNoWait"
                  ExeCommand="${cmd(`/c sc.exe start ${L.serviceName} &gt;nul 2&gt;&amp;1`)}" />
    <!-- A full uninstall removes the data folder: the spool, the credential, the logs and the copied
         tenant.env are not installed files. An upgrade keeps them. -->
    <CustomAction Id="RemoveData" Directory="CommonAppDataFolder" Execute="deferred" Impersonate="no" Return="ignore"
                  ExeCommand="${cmd('/c rmdir /s /q &quot;[DATAFOLDER]&quot;')}" />
    <InstallExecuteSequence>
      <ResolveSource After="CostInitialize" Condition="NOT Installed" />
      <Custom Action="CheckTenantConfig" After="CostFinalize" Condition="NOT Installed" />
      <Custom Action="StartService" After="InstallServices" Condition="NOT REMOVE" />
      <Custom Action="RemoveData" After="RemoveFiles" Condition="REMOVE=&quot;ALL&quot; AND NOT UPGRADINGPRODUCTCODE" />
    </InstallExecuteSequence>

    <Feature Id="Main" Title="${PRODUCT.displayName}" Level="1">
      <ComponentGroupRef Id="Product" />
    </Feature>
  </Package>
</Wix>
`;
}

export const FILES = [
  { path: `${TENANT_PACKAGE.fileName}.example`, render: tenantEnvExample },
  { path: 'linux/shadow-ai-capture.service', render: () => systemdUnit(LAYOUT.linux) },
  { path: `linux/${HOST_FILE}`, render: () => nativeHostJson('linux') },
  { path: 'macos/com.shadowaicapture.capture-core.plist', render: () => launchdPlist(LAYOUT.darwin) },
  { path: `macos/${HOST_FILE}`, render: () => nativeHostJson('darwin') },
  { path: 'windows/ShadowAICapture.wxs', render: wixSource },
  { path: `windows/${HOST_FILE}`, render: () => nativeHostJson('windows') },
];

/** Generated files that differ from the manifest, by path. */
export function drift() {
  return FILES.filter((f) => {
    const abs = join(GENERATED, f.path);
    return !existsSync(abs) || readFileSync(abs, 'utf8') !== f.render();
  }).map((f) => f.path);
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const args = process.argv.slice(2);
  if (args.includes('--list')) {
    for (const c of CONFIG) {
      console.log(`${c.env.padEnd(24)} ${c.flag.padEnd(22)}${c.required ? ' required' : ''}${c.scope ? ` ${c.scope}` : ''}`);
      console.log(`  ${c.desc}`);
    }
  } else if (args.includes('--check')) {
    const drifted = drift();
    for (const f of drifted) console.error(`drift: device/installer/generated/${f}`);
    if (drifted.length) {
      console.error('device/installer/generated differs from device/installer/manifest.mjs; run: node device/installer/render.mjs');
      process.exit(1);
    }
    console.log(`device/installer/generated matches device/installer/manifest.mjs (${FILES.length} files)`);
  } else {
    for (const f of FILES) {
      const abs = join(GENERATED, f.path);
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, f.render());
      console.log(`write device/installer/generated/${f.path}`);
    }
  }
}
