-- generated by content-vault schema-sql; every statement the service issues.
\set ON_ERROR_STOP on
BEGIN;

-- set_tenant: RLS session tenant (transaction-local)
PREPARE set_tenant AS SELECT set_config('app.tenant_id', $1::text, true);
DEALLOCATE set_tenant;

-- tenant: custody + search tier + gates for the tenant
PREPARE tenant AS 
SELECT tenant_id::text, name, status, key_custody, COALESCE(kek_id, ''), ceiling_mode,
       content_search, ingest_enabled, read_enabled
  FROM ops.tenant
 WHERE tenant_id = $1::uuid;
DEALLOCATE tenant;

-- put_content_object: store the wrapped DEK beside the blob reference
PREPARE put_content_object AS 
INSERT INTO ops.content_object (
    tenant_id, object_id, submission_id, event_id, blob_path, ciphertext_sha256,
    plaintext_size_bytes, wrapped_dek, kek_id, kek_version, retention_class, state,
    created_at, expires_at)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::text, $6::text,
        $7::bigint, $8::bytea, $9::text, $10::text, $11::text, 'uploaded',
        $12::timestamptz, $13::timestamptz)
ON CONFLICT (tenant_id, object_id) DO UPDATE
   SET submission_id        = EXCLUDED.submission_id,
       event_id             = EXCLUDED.event_id,
       blob_path            = EXCLUDED.blob_path,
       ciphertext_sha256    = EXCLUDED.ciphertext_sha256,
       plaintext_size_bytes = EXCLUDED.plaintext_size_bytes,
       wrapped_dek          = EXCLUDED.wrapped_dek,
       kek_id               = EXCLUDED.kek_id,
       kek_version          = EXCLUDED.kek_version,
       retention_class      = EXCLUDED.retention_class,
       state                = 'uploaded',
       expires_at           = EXCLUDED.expires_at
 WHERE ops.content_object.state <> 'shredded'
RETURNING object_id::text;
DEALLOCATE put_content_object;

-- content_object: read one object by id
PREPARE content_object AS 
SELECT tenant_id::text, object_id::text, COALESCE(submission_id::text, ''), COALESCE(event_id::text, ''),
       blob_path, ciphertext_sha256, plaintext_size_bytes, wrapped_dek, kek_id, kek_version,
       retention_class, state, COALESCE(shredded_reason, ''), created_at, expires_at, shredded_at
  FROM ops.content_object
 WHERE tenant_id = $1::uuid AND object_id = $2::uuid;
DEALLOCATE content_object;

-- object_for_event: resolve an event's object (the retrieval path)
PREPARE object_for_event AS 
SELECT tenant_id::text, object_id::text, COALESCE(submission_id::text, ''), COALESCE(event_id::text, ''),
       blob_path, ciphertext_sha256, plaintext_size_bytes, wrapped_dek, kek_id, kek_version,
       retention_class, state, COALESCE(shredded_reason, ''), created_at, expires_at, shredded_at
  FROM ops.content_object
 WHERE tenant_id = $1::uuid AND event_id = $2::uuid
 ORDER BY created_at DESC
 LIMIT 1;
DEALLOCATE object_for_event;

-- objects_for_tenant: list what a rotation must re-wrap
PREPARE objects_for_tenant AS 
SELECT tenant_id::text, object_id::text, COALESCE(submission_id::text, ''), COALESCE(event_id::text, ''),
       blob_path, ciphertext_sha256, plaintext_size_bytes, wrapped_dek, kek_id, kek_version,
       retention_class, state, COALESCE(shredded_reason, ''), created_at, expires_at, shredded_at
  FROM ops.content_object
 WHERE tenant_id = $1::uuid AND state = 'uploaded'
 ORDER BY object_id;
DEALLOCATE objects_for_tenant;

-- rewrap_object: rotation: re-wrap, never re-encrypt
PREPARE rewrap_object AS 
UPDATE ops.content_object
   SET wrapped_dek = $4::bytea,
       kek_version = $5::text
 WHERE tenant_id = $1::uuid AND object_id = $2::uuid
   AND kek_version = $3::text
   AND state = 'uploaded';
DEALLOCATE rewrap_object;

-- shred_object: erasure: destroy the wrapped key and record the shred
PREPARE shred_object AS 
UPDATE ops.content_object
   SET state = 'shredded',
       shredded_reason = $3::text,
       shredded_at = $4::timestamptz,
       wrapped_dek = '\x00'::bytea
 WHERE tenant_id = $1::uuid AND object_id = $2::uuid AND state = 'uploaded';
DEALLOCATE shred_object;

-- put_search_unit: write one ingest.search_text row
PREPARE put_search_unit AS 
INSERT INTO ingest.search_text (tenant_id, submission_id, unit_kind, unit_index, body, expires_at)
VALUES ($1::uuid, $2::uuid, $3::text, $4::int, $5::text, $6::timestamptz)
ON CONFLICT (tenant_id, submission_id, unit_kind, unit_index) DO UPDATE
   SET body = EXCLUDED.body,
       expires_at = EXCLUDED.expires_at;
DEALLOCATE put_search_unit;

-- delete_search_text_submission: erasure reaches the index by row deletion
PREPARE delete_search_text_submission AS 
DELETE FROM ingest.search_text WHERE tenant_id = $1::uuid AND submission_id = $2::uuid;
DEALLOCATE delete_search_text_submission;

-- delete_search_text_tenant: offboarding: every index row of a tenant
PREPARE delete_search_text_tenant AS 
DELETE FROM ingest.search_text WHERE tenant_id = $1::uuid;
DEALLOCATE delete_search_text_tenant;

-- search_terms: §15.3 term/phrase form over tsv
PREPARE search_terms AS 
SELECT submission_id::text,
       unit_kind,
       unit_index,
       ts_headline('simple', body, to_tsquery('simple', $2::text),
                   'StartSel=<em>, StopSel=</em>, MaxFragments=1, MaxWords=24, MinWords=6, FragmentDelimiter= … '),
       ts_rank(tsv, to_tsquery('simple', $2::text))
  FROM ingest.search_text
 WHERE tenant_id = $1::uuid
   AND tsv @@ to_tsquery('simple', $2::text)
   AND ($3::text = '' OR unit_kind = $3::text)
 ORDER BY 5 DESC, 1
 LIMIT $4::int;
DEALLOCATE search_terms;

-- search_substring: §15.3 substring form over filenames
PREPARE search_substring AS 
SELECT submission_id::text,
       unit_kind,
       unit_index,
       body,
       similarity(lower(body), lower($2::text))
  FROM ingest.search_text
 WHERE tenant_id = $1::uuid
   AND unit_kind = 'attachment_name'
   AND lower(body) LIKE '%' || lower($2::text) || '%'
 ORDER BY 5 DESC, 1
 LIMIT $3::int;
DEALLOCATE search_substring;

-- search_fuzzy: §15.3 fuzzy form over filenames
PREPARE search_fuzzy AS 
SELECT submission_id::text,
       unit_kind,
       unit_index,
       body,
       similarity(lower(body), lower($2::text))
  FROM ingest.search_text
 WHERE tenant_id = $1::uuid
   AND unit_kind = 'attachment_name'
   AND lower(body) % lower($2::text)
   AND similarity(lower(body), lower($2::text)) >= $3::float8
 ORDER BY 5 DESC, 1
 LIMIT $4::int;
DEALLOCATE search_fuzzy;

-- insert_audit: audit-before-serve; the chain trigger fills the hashes
PREPARE insert_audit AS 
INSERT INTO ops.audit (tenant_id, actor_type, actor_id, action, object_type, object_id,
                       subject_ref, case_reference, detail, occurred_at)
VALUES ($1::uuid, $2::text, $3::text, $4::text, $5::text, $6::text,
        $7::text, $8::text, $9::jsonb, $10::timestamptz);
DEALLOCATE insert_audit;

-- put_erasure_receipt: the receipt C34 requires
PREPARE put_erasure_receipt AS 
INSERT INTO ops.erasure_receipt (tenant_id, receipt_id, scope_kind, subject_ref, requested_by,
                                 requested_at, completed_at, mechanisms, removed_counts, remaining_counts)
VALUES ($1::uuid, $2::uuid, $3::text, $4::text, $5::text, $6::timestamptz, $7::timestamptz,
        $8::text[], $9::jsonb, $10::jsonb);
DEALLOCATE put_erasure_receipt;

-- last_receipt: link a no_longer_available result to its receipt
PREPARE last_receipt AS 
SELECT tenant_id::text, receipt_id::text, scope_kind, subject_ref, requested_by, requested_at,
       completed_at, array_to_string(mechanisms, ','), removed_counts, remaining_counts
  FROM ops.erasure_receipt
 WHERE tenant_id = $1::uuid
 ORDER BY completed_at DESC NULLS LAST, requested_at DESC
 LIMIT 1;
DEALLOCATE last_receipt;

-- put_retrieval_grant: record a single-use retrieval grant
PREPARE put_retrieval_grant AS 
INSERT INTO ops.retrieval_grant (tenant_id, grant_id, event_id, object_id, submission_id,
                                 principal, case_reference, second_approver, issued_at, expires_at, raw_digest)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, $5::uuid, $6::text, $7::text, $8::text,
        $9::timestamptz, $10::timestamptz, $11::text);
DEALLOCATE put_retrieval_grant;

-- retrieval_grant: read a retrieval grant
PREPARE retrieval_grant AS 
SELECT tenant_id::text, grant_id::text, event_id::text, object_id::text, submission_id::text,
       principal, case_reference, second_approver, issued_at, expires_at, used_at, COALESCE(used_by, ''), raw_digest
  FROM ops.retrieval_grant
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid;
DEALLOCATE retrieval_grant;

-- claim_retrieval_grant: consume it atomically (UPDATE ... WHERE used_at IS NULL)
PREPARE claim_retrieval_grant AS 
UPDATE ops.retrieval_grant
   SET used_at = $3::timestamptz,
       used_by = $4::text
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid AND used_at IS NULL
RETURNING tenant_id::text, grant_id::text, event_id::text, object_id::text, submission_id::text,
          principal, case_reference, second_approver, issued_at, expires_at, used_at, COALESCE(used_by, ''), raw_digest;
DEALLOCATE claim_retrieval_grant;

ROLLBACK;

-- The retrieval-grant table this service needs and the schema does not yet have:
-- 
-- CREATE TABLE ops.retrieval_grant (
--   tenant_id       uuid NOT NULL REFERENCES ops.tenant(tenant_id),
--   grant_id        uuid NOT NULL,
--   event_id        uuid NOT NULL,
--   object_id       uuid NOT NULL,
--   submission_id   uuid NOT NULL,
--   principal       text NOT NULL,
--   case_reference  text NOT NULL,
--   second_approver text NOT NULL,
--   issued_at       timestamptz NOT NULL,
--   expires_at      timestamptz NOT NULL,
--   used_at         timestamptz,
--   used_by         text,
--   raw_digest      text NOT NULL,
--   PRIMARY KEY (tenant_id, grant_id),
--   CONSTRAINT retrieval_grant_second_approver_distinct CHECK (second_approver <> principal),
--   CONSTRAINT retrieval_grant_window_bounded CHECK (expires_at > issued_at)
-- );
