/* dsh-project-cockpit — client bundle. Generated by .cockpit/tools/build-client.mjs; edit .cockpit/lib/client/*.js instead. */
window.__ModuleLoader__.load({
	id: "dsh-project-cockpit",
	factory: (require) => {
		var module = { exports: {} };
		var exports = module.exports;
		Object.defineProperty(exports, Symbol.toStringTag, { value: "Module" });

		// ---- lib/client/styles.js ----
		/**
		 * Project Cockpit — the panel's stylesheet.
		 *
		 * Kept as one string so the client bundle stays a single self-contained file
		 * with no build step. Every colour resolves through a host theme token with a
		 * literal fallback, so the panel follows light/dark like the rest of the shell
		 * and still renders if a token is renamed.
		 */
		
		/** Short prefix for every class, so two plugins cannot collide in the page. */
		const P = 'pcx'
		
		const CLASS = {
		  root: `${P}-root`,
		  header: `${P}-header`,
		  title: `${P}-title`,
		  subtitle: `${P}-subtitle`,
		  chipRow: `${P}-chips`,
		  chip: `${P}-chip`,
		  chipDot: `${P}-chipdot`,
		  actions: `${P}-actions`,
		  button: `${P}-button`,
		  buttonPrimary: `${P}-button-primary`,
		  body: `${P}-body`,
		  tabs: `${P}-tabs`,
		  tab: `${P}-tab`,
		  tabActive: `${P}-tab-active`,
		  tabCount: `${P}-tabcount`,
		  view: `${P}-view`,
		  section: `${P}-section`,
		  sectionTitle: `${P}-section-title`,
		  muted: `${P}-muted`,
		  grid: `${P}-grid`,
		  card: `${P}-card`,
		  cardHeader: `${P}-cardheader`,
		  cardTitle: `${P}-cardtitle`,
		  cardMeta: `${P}-cardmeta`,
		  bar: `${P}-bar`,
		  barSeg: `${P}-barseg`,
		  legend: `${P}-legend`,
		  legendItem: `${P}-legenditem`,
		  swatch: `${P}-swatch`,
		  layer: `${P}-layer`,
		  layerHead: `${P}-layerhead`,
		  layerName: `${P}-layername`,
		  layerRule: `${P}-layerrule`,
		  nodes: `${P}-nodes`,
		  node: `${P}-node`,
		  nodeActive: `${P}-node-active`,
		  nodeTop: `${P}-nodetop`,
		  nodeName: `${P}-nodename`,
		  nodeKind: `${P}-nodekind`,
		  nodeDeps: `${P}-nodedeps`,
		  badge: `${P}-badge`,
		  dot: `${P}-dot`,
		  mono: `${P}-mono`,
		  table: `${P}-table`,
		  row: `${P}-row`,
		  rowClick: `${P}-rowclick`,
		  cell: `${P}-cell`,
		  cols: `${P}-cols`,
		  col: `${P}-col`,
		  list: `${P}-list`,
		  listItem: `${P}-listitem`,
		  missing: `${P}-missing`,
		  present: `${P}-present`,
		  warn: `${P}-warn`,
		  warnBox: `${P}-warnbox`,
		  empty: `${P}-empty`,
		  agent: `${P}-agent`,
		  agentRow: `${P}-agentrow`,
		  agentCard: `${P}-agentcard`,
		  agentName: `${P}-agentname`,
		  agentRole: `${P}-agentrole`,
		  emoji: `${P}-emoji`,
		  task: `${P}-task`,
		  taskCard: `${P}-taskcard`,
		  taskHead: `${P}-taskhead`,
		  taskBody: `${P}-taskbody`,
		  deps: `${P}-deps`,
		  dep: `${P}-dep`,
		  arrow: `${P}-arrow`,
		  kpi: `${P}-kpi`,
		  kpiValue: `${P}-kpivalue`,
		  kpiLabel: `${P}-kpilabel`,
		  tree: `${P}-tree`,
		  treeRow: `${P}-treerow`,
		  treeName: `${P}-treename`,
		  treeMeta: `${P}-treemeta`,
		  footer: `${P}-footer`,
		  spin: `${P}-spin`,
		  err: `${P}-err`,
		  ok: `${P}-ok`,
		  invariants: `${P}-invariants`,
		  inv: `${P}-inv`,
		  invId: `${P}-invid`,
		  tag: `${P}-tag`,
		  scroll: `${P}-scroll`,
		  details: `${P}-details`,
		  summary: `${P}-summary`,
		  heading: `${P}-heading`,
		  headingL2: `${P}-heading-l2`,
		  headingL3: `${P}-heading-l3`,
		}
		
		/**
		 * The stylesheet text.
		 * @returns CSS.
		 */
		function cockpitCss() {
		  return `
		.${CLASS.root} {
		  --pcx-bg: var(--dsw-alias-bg-base, #16171a);
		  --pcx-surface: var(--dsw-alias-bg-layer-1, #1d1f23);
		  --pcx-surface2: var(--dsw-alias-bg-layer-2, #24272c);
		  --pcx-overlay: var(--dsw-alias-bg-overlay, #2a2e34);
		  --pcx-line: var(--dsw-alias-border-l1, #31353c);
		  --pcx-line2: var(--dsw-alias-border-l2, #3d434c);
		  --pcx-text: var(--dsw-alias-label-primary, #e8eaed);
		  --pcx-text2: var(--dsw-alias-label-secondary, #a2a9b4);
		  --pcx-brand: var(--dsw-alias-brand-primary, #4d8dff);
		  --pcx-ok: var(--dsw-alias-state-success-primary, #3fb950);
		  --pcx-warn: var(--dsw-alias-state-warn-primary, #d29922);
		  --pcx-err: var(--dsw-alias-state-error-primary, #f85149);
		  --pcx-idle: var(--dsw-alias-state-idle-primary, #8b949e);
		  --pcx-radius: 10px;
		  display: flex;
		  flex-direction: column;
		  height: 100%;
		  min-height: 0;
		  background: var(--pcx-bg);
		  color: var(--pcx-text);
		  font-size: 13px;
		  line-height: 1.45;
		}
		
		.${CLASS.header} {
		  flex: none;
		  padding: 16px 20px 0;
		  border-bottom: 1px solid var(--pcx-line);
		  background: var(--pcx-surface);
		}
		
		.${CLASS.title} {
		  margin: 0;
		  font-size: 17px;
		  font-weight: 600;
		  letter-spacing: -0.01em;
		  display: flex;
		  align-items: baseline;
		  gap: 10px;
		  flex-wrap: wrap;
		}
		
		.${CLASS.subtitle} {
		  color: var(--pcx-text2);
		  font-size: 12.5px;
		  margin: 4px 0 0;
		  max-width: 90ch;
		}
		
		.${CLASS.chipRow} {
		  display: flex;
		  flex-wrap: wrap;
		  gap: 6px;
		  margin: 10px 0 0;
		}
		
		.${CLASS.chip} {
		  display: inline-flex;
		  align-items: center;
		  gap: 6px;
		  padding: 3px 9px;
		  border: 1px solid var(--pcx-line);
		  border-radius: 999px;
		  background: var(--pcx-surface2);
		  color: var(--pcx-text2);
		  font-size: 11.5px;
		  white-space: nowrap;
		}
		
		.${CLASS.chipDot} {
		  width: 7px;
		  height: 7px;
		  border-radius: 50%;
		  flex: none;
		}
		
		.${CLASS.actions} {
		  display: flex;
		  gap: 8px;
		  align-items: center;
		  margin: 12px 0 0;
		}
		
		.${CLASS.button} {
		  appearance: none;
		  border: 1px solid var(--pcx-line2);
		  background: var(--pcx-surface2);
		  color: var(--pcx-text);
		  border-radius: 7px;
		  padding: 4px 11px;
		  font-size: 12px;
		  font-family: inherit;
		  cursor: pointer;
		}
		
		.${CLASS.button}:hover { border-color: var(--pcx-brand); }
		.${CLASS.button}:disabled { opacity: 0.55; cursor: default; }
		
		.${CLASS.buttonPrimary} {
		  background: var(--pcx-brand);
		  border-color: var(--pcx-brand);
		  color: #fff;
		}
		
		.${CLASS.tabs} {
		  display: flex;
		  gap: 2px;
		  margin-top: 12px;
		  overflow-x: auto;
		  scrollbar-width: none;
		}
		
		.${CLASS.tabs}::-webkit-scrollbar { display: none; }
		
		.${CLASS.tab} {
		  appearance: none;
		  border: 0;
		  border-bottom: 2px solid transparent;
		  background: transparent;
		  color: var(--pcx-text2);
		  font-family: inherit;
		  font-size: 12.5px;
		  padding: 7px 11px;
		  cursor: pointer;
		  display: inline-flex;
		  align-items: center;
		  gap: 6px;
		  white-space: nowrap;
		}
		
		.${CLASS.tab}:hover { color: var(--pcx-text); }
		.${CLASS.tabActive} { color: var(--pcx-text); border-bottom-color: var(--pcx-brand); }
		
		.${CLASS.tabCount} {
		  font-variant-numeric: tabular-nums;
		  font-size: 11px;
		  color: var(--pcx-text2);
		  background: var(--pcx-surface2);
		  border-radius: 999px;
		  padding: 0 6px;
		}
		
		.${CLASS.body} {
		  flex: 1 1 auto;
		  min-height: 0;
		  overflow-y: auto;
		  padding: 18px 20px 32px;
		  scrollbar-gutter: stable;
		}
		
		.${CLASS.view} { display: flex; flex-direction: column; gap: 18px; }
		
		.${CLASS.section} {
		  border: 1px solid var(--pcx-line);
		  border-radius: var(--pcx-radius);
		  background: var(--pcx-surface);
		  padding: 14px 16px;
		}
		
		.${CLASS.sectionTitle} {
		  margin: 0 0 10px;
		  font-size: 12px;
		  font-weight: 600;
		  text-transform: uppercase;
		  letter-spacing: 0.06em;
		  color: var(--pcx-text2);
		}
		
		.${CLASS.kpi} {
		  display: flex;
		  gap: 22px;
		  flex-wrap: wrap;
		}
		
		.${CLASS.kpiValue} {
		  font-size: 21px;
		  font-weight: 600;
		  font-variant-numeric: tabular-nums;
		}
		
		.${CLASS.kpiLabel} {
		  font-size: 11px;
		  color: var(--pcx-text2);
		  text-transform: uppercase;
		  letter-spacing: 0.05em;
		}
		
		.${CLASS.bar} {
		  display: flex;
		  height: 12px;
		  border-radius: 999px;
		  overflow: hidden;
		  background: var(--pcx-surface2);
		  border: 1px solid var(--pcx-line);
		}
		
		.${CLASS.barSeg} { height: 100%; min-width: 2px; }
		
		.${CLASS.legend} {
		  display: flex;
		  flex-wrap: wrap;
		  gap: 12px;
		  margin-top: 10px;
		}
		
		.${CLASS.legendItem} {
		  display: inline-flex;
		  align-items: center;
		  gap: 6px;
		  font-size: 11.5px;
		  color: var(--pcx-text2);
		}
		
		.${CLASS.swatch} { width: 9px; height: 9px; border-radius: 3px; flex: none; }
		
		.${CLASS.layer} { display: flex; flex-direction: column; gap: 10px; }
		
		.${CLASS.layerHead} { display: flex; align-items: center; gap: 10px; }
		
		.${CLASS.layerName} {
		  font-size: 12px;
		  font-weight: 600;
		  text-transform: uppercase;
		  letter-spacing: 0.07em;
		  color: var(--pcx-text2);
		  white-space: nowrap;
		}
		
		.${CLASS.layerRule} { flex: 1; height: 1px; background: var(--pcx-line); }
		
		.${CLASS.nodes} {
		  display: grid;
		  grid-template-columns: repeat(auto-fill, minmax(238px, 1fr));
		  gap: 10px;
		}
		
		.${CLASS.node} {
		  border: 1px solid var(--pcx-line);
		  border-left-width: 3px;
		  border-radius: 8px;
		  background: var(--pcx-surface2);
		  padding: 9px 11px;
		  cursor: pointer;
		  text-align: left;
		  font-family: inherit;
		  color: inherit;
		  display: flex;
		  flex-direction: column;
		  gap: 5px;
		  min-width: 0;
		}
		
		.${CLASS.node}:hover { border-color: var(--pcx-line2); background: var(--pcx-overlay); }
		.${CLASS.nodeActive} { box-shadow: 0 0 0 1px var(--pcx-brand) inset; }
		
		.${CLASS.nodeTop} { display: flex; align-items: center; gap: 7px; min-width: 0; }
		
		.${CLASS.nodeName} {
		  font-weight: 600;
		  font-size: 13px;
		  overflow: hidden;
		  text-overflow: ellipsis;
		  white-space: nowrap;
		  flex: 1;
		}
		
		.${CLASS.nodeKind} { font-size: 11px; color: var(--pcx-text2); font-family: ui-monospace, SFMono-Regular, Menlo, monospace; }
		
		.${CLASS.nodeDeps} { font-size: 11px; color: var(--pcx-text2); overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
		
		.${CLASS.badge} {
		  display: inline-flex;
		  align-items: center;
		  gap: 5px;
		  border-radius: 999px;
		  padding: 1px 8px;
		  font-size: 11px;
		  border: 1px solid var(--pcx-line2);
		  color: var(--pcx-text2);
		  white-space: nowrap;
		}
		
		.${CLASS.dot} { width: 8px; height: 8px; border-radius: 50%; flex: none; }
		
		.${CLASS.mono} { font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace; font-size: 11.5px; }
		
		.${CLASS.grid} {
		  display: grid;
		  grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));
		  gap: 12px;
		}
		
		.${CLASS.card} {
		  border: 1px solid var(--pcx-line);
		  border-radius: var(--pcx-radius);
		  background: var(--pcx-surface);
		  padding: 12px 14px;
		  min-width: 0;
		}
		
		.${CLASS.cardHeader} { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
		
		.${CLASS.cardTitle} { font-weight: 600; font-size: 13.5px; display: flex; align-items: center; gap: 7px; }
		
		.${CLASS.cardMeta} { color: var(--pcx-text2); font-size: 11.5px; margin-top: 3px; }
		
		.${CLASS.cols} { display: grid; grid-template-columns: repeat(auto-fit, minmax(260px, 1fr)); gap: 14px; }
		
		.${CLASS.col} { min-width: 0; display: flex; flex-direction: column; gap: 8px; }
		
		.${CLASS.list} { display: flex; flex-direction: column; gap: 5px; }
		
		.${CLASS.listItem} {
		  display: flex;
		  align-items: center;
		  gap: 8px;
		  font-size: 12px;
		  min-width: 0;
		}
		
		.${CLASS.treeRow} {
		  display: flex;
		  align-items: center;
		  gap: 8px;
		  padding: 2px 6px;
		  border-radius: 5px;
		  font-size: 12px;
		  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
		  min-width: 0;
		}
		
		.${CLASS.treeRow}:hover { background: var(--pcx-surface2); }
		.${CLASS.treeName} { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
		.${CLASS.treeMeta} { color: var(--pcx-text2); font-size: 11px; white-space: nowrap; }
		
		.${CLASS.present} { color: var(--pcx-ok); }
		.${CLASS.missing} { color: var(--pcx-err); }
		.${CLASS.warn} { color: var(--pcx-warn); }
		.${CLASS.ok} { color: var(--pcx-ok); }
		.${CLASS.err} { color: var(--pcx-err); }
		.${CLASS.muted} { color: var(--pcx-text2); }
		
		.${CLASS.warnBox} {
		  border: 1px solid var(--pcx-warn);
		  border-radius: 8px;
		  background: color-mix(in srgb, var(--pcx-warn) 9%, transparent);
		  padding: 9px 12px;
		  font-size: 12px;
		}
		
		.${CLASS.err} { color: var(--pcx-err); }
		
		.${CLASS.empty} {
		  border: 1px dashed var(--pcx-line2);
		  border-radius: var(--pcx-radius);
		  padding: 26px 18px;
		  text-align: center;
		  color: var(--pcx-text2);
		  font-size: 12.5px;
		}
		
		.${CLASS.agentRow} {
		  display: flex;
		  align-items: center;
		  gap: 9px;
		  padding: 7px 9px;
		  border: 1px solid var(--pcx-line);
		  border-radius: 8px;
		  background: var(--pcx-surface2);
		  cursor: pointer;
		  font-family: inherit;
		  color: inherit;
		  text-align: left;
		  width: 100%;
		}
		
		.${CLASS.agentRow}:hover { border-color: var(--pcx-line2); }
		.${CLASS.emoji} { font-size: 16px; flex: none; }
		.${CLASS.agentName} { font-weight: 600; font-size: 12.5px; }
		.${CLASS.agentRole} { color: var(--pcx-text2); font-size: 11.5px; }
		
		.${CLASS.deps} { display: flex; flex-wrap: wrap; gap: 5px; align-items: center; }
		.${CLASS.dep} { border: 1px solid var(--pcx-line2); border-radius: 5px; padding: 0 6px; font-size: 11px; font-family: ui-monospace, monospace; color: var(--pcx-text2); }
		.${CLASS.arrow} { color: var(--pcx-text2); font-size: 11px; }
		
		.${CLASS.taskCard} {
		  border: 1px solid var(--pcx-line);
		  border-left-width: 3px;
		  border-radius: 8px;
		  background: var(--pcx-surface);
		  padding: 10px 12px;
		  display: flex;
		  flex-direction: column;
		  gap: 7px;
		  min-width: 0;
		}
		
		.${CLASS.taskHead} { display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }
		.${CLASS.taskBody} { font-size: 12px; color: var(--pcx-text2); }
		
		.${CLASS.inv} {
		  display: flex;
		  gap: 9px;
		  align-items: flex-start;
		  padding: 6px 0;
		  border-top: 1px solid var(--pcx-line);
		  font-size: 12px;
		}
		
		.${CLASS.invId} {
		  flex: none;
		  font-family: ui-monospace, monospace;
		  font-size: 11px;
		  color: var(--pcx-text2);
		  min-width: 54px;
		}
		
		.${CLASS.tag} {
		  font-size: 10.5px;
		  border: 1px solid var(--pcx-line2);
		  border-radius: 4px;
		  padding: 0 5px;
		  color: var(--pcx-text2);
		}
		
		.${CLASS.details} { font-size: 12px; }
		.${CLASS.summary} { cursor: pointer; color: var(--pcx-text2); }
		.${CLASS.summary}:hover { color: var(--pcx-text); }
		
		.${CLASS.heading} { font-size: 14px; font-weight: 600; margin: 0; }
		.${CLASS.headingL2} { margin: 12px 0 4px; font-size: 12.5px; font-weight: 600; }
		.${CLASS.headingL3} { margin: 10px 0 4px; font-size: 12px; font-weight: 600; color: var(--pcx-text2); }
		
		.${CLASS.footer} {
		  flex: none;
		  border-top: 1px solid var(--pcx-line);
		  padding: 7px 20px;
		  font-size: 11px;
		  color: var(--pcx-text2);
		  display: flex;
		  gap: 14px;
		  flex-wrap: wrap;
		  background: var(--pcx-surface);
		}
		
		.${CLASS.table} { display: flex; flex-direction: column; gap: 2px; }
		.${CLASS.row} { display: flex; gap: 10px; align-items: center; padding: 3px 6px; border-radius: 5px; font-size: 12px; min-width: 0; }
		.${CLASS.rowClick} { cursor: pointer; font-family: inherit; color: inherit; border: 0; background: transparent; text-align: left; width: 100%; }
		.${CLASS.rowClick}:hover { background: var(--pcx-surface2); }
		.${CLASS.cell} { min-width: 0; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
		`
		}
		
		// ---- lib/client/viewmodel.js ----
		/**
		 * Project Cockpit — client-side derivation.
		 *
		 * Pure functions that turn the host's project index plus the live team
		 * projection into the numbers and groupings the panels render. No React, no
		 * fetch, no host APIs: if a figure in the cockpit is wrong, the reason is in
		 * here and it can be tested without a browser.
		 */
		
		/** Status → display colour variable, shared by components, tasks and agents. */
		const STATUS_COLOR = {
		  done: 'var(--pcx-ok)',
		  completed: 'var(--pcx-ok)',
		  'in-progress': 'var(--pcx-brand)',
		  in_progress: 'var(--pcx-brand)',
		  scaffolded: 'var(--pcx-warn)',
		  running: 'var(--pcx-ok)',
		  pending: 'var(--pcx-idle)',
		  proposed: 'var(--pcx-idle)',
		  inactive: 'var(--pcx-idle)',
		  provisioning: 'var(--pcx-warn)',
		  blocked: 'var(--pcx-err)',
		  failed: 'var(--pcx-err)',
		  cut: 'var(--pcx-idle)',
		  active: 'var(--pcx-ok)',
		}
		
		/** Status → human label. */
		const STATUS_LABEL = {
		  'in-progress': 'in progress',
		  in_progress: 'in progress',
		  done: 'done',
		  completed: 'completed',
		  scaffolded: 'scaffolded',
		  proposed: 'proposed',
		  blocked: 'blocked',
		  cut: 'cut',
		  pending: 'pending',
		  running: 'running',
		  inactive: 'inactive',
		  provisioning: 'provisioning',
		  failed: 'failed',
		  active: 'active',
		}
		
		/**
		 * Resolve a status to its colour, falling back to the muted idle colour.
		 * @param status raw status string.
		 * @returns a CSS colour value.
		 */
		function statusColor(status) {
		  return STATUS_COLOR[status] ?? 'var(--pcx-idle)'
		}
		
		/**
		 * Resolve a status to a readable label.
		 * @param status raw status string.
		 * @returns a label.
		 */
		function statusLabel(status) {
		  if (status === undefined || status === null || status === '') return 'unknown'
		  return STATUS_LABEL[status] ?? String(status).replace(/[_-]/gu, ' ')
		}
		
		/**
		 * Count components by status, in a fixed display order.
		 * @param components component rows.
		 * @returns `{ segments, total }` where each segment carries its share.
		 */
		function statusBreakdown(components) {
		  const order = ['done', 'in-progress', 'scaffolded', 'proposed', 'blocked', 'cut']
		  const counts = new Map(order.map((status) => [status, 0]))
		  for (const component of components) {
		    const status = order.includes(component.status) ? component.status : 'proposed'
		    counts.set(status, (counts.get(status) ?? 0) + 1)
		  }
		  const total = components.length
		  const segments = order
		    .map((status) => ({
		      status,
		      label: statusLabel(status),
		      count: counts.get(status) ?? 0,
		      color: statusColor(status),
		      share: total === 0 ? 0 : (counts.get(status) ?? 0) / total,
		    }))
		    .filter((segment) => segment.count > 0)
		  return { segments, total }
		}
		
		/**
		 * Group components by their declared layer, preserving first-seen layer order.
		 * @param components component rows.
		 * @param layers the layer order the host derived.
		 * @returns `[{ layer, components }]`.
		 */
		function groupByLayer(components, layers) {
		  const order = [...(layers ?? [])]
		  for (const component of components) if (!order.includes(component.layer)) order.push(component.layer)
		  return order
		    .map((layer) => ({ layer, components: components.filter((component) => component.layer === layer) }))
		    .filter((group) => group.components.length > 0)
		}
		
		/**
		 * How far through the plan the project is, by component count.
		 * @param components component rows.
		 * @returns `{ pct, done, total }`.
		 */
		function planProgress(components) {
		  const total = components.length
		  const done = components.filter((component) => component.status === 'done').length
		  return { pct: total === 0 ? 0 : Math.round((done / total) * 100), done, total }
		}
		
		/**
		 * The project's headline numbers.
		 * @param index the host's project index.
		 * @returns KPI rows.
		 */
		function kpis(index) {
		  const reachable = index.components.filter((component) => component.status !== 'cut').length
		  const ready = index.tasks.filter((task) => task.status === 'pending' && !task.blocked).length
		  const complete = index.tasks.filter((task) => task.status === 'completed').length
		  return [
		    { label: 'components', value: `${reachable}`, hint: `${index.layers.length} layers` },
		    { label: 'agents', value: `${index.agents.length}`, hint: 'planned roster' },
		    { label: 'tasks', value: `${complete}/${index.tasks.length}`, hint: `${ready} ready` },
		    { label: 'files on disk', value: `${index.stats.files}`, hint: `${index.unownedFiles.length} unclaimed` },
		    { label: 'declared paths absent', value: `${index.stats.missingPaths}`, hint: `${index.stats.declaredPaths} declared` },
		  ]
		}
		
		/**
		 * Everything the reader needs to know is wrong, in one list. Each row names a
		 * concrete consequence rather than restating the raw data.
		 * @param index the host's project index.
		 * @param team live team state, when a session is open.
		 * @returns warning rows `{ level, text }`.
		 */
		function warnings(index, team) {
		  const rows = []
		  if (index.truncated) {
		    rows.push({ level: 'warn', text: 'The workspace scan was truncated — the file list is partial.' })
		  }
		  if (!index.hasManifest) {
		    rows.push({ level: 'err', text: `No manifest found. The cockpit is showing the raw workspace tree; create ${index.manifestPath} to declare the architecture.` })
		  }
		  for (const collision of index.collisions) {
		    rows.push({ level: 'warn', text: `Write-scope overlap: ${collision.a} and ${collision.b} both claim ${collision.left} / ${collision.right}.` })
		  }
		  for (const component of index.components) {
		    if (component.status !== 'cut' && component.missingPaths > 0) {
		      rows.push({ level: 'warn', text: `${component.id} declares ${component.missingPaths} path(s) that are not on disk.` })
		    }
		  }
		  for (const task of index.tasks) {
		    // A pending task with unfinished dependencies is the plan working, not a
		    // problem — that is what a dependency is for. Only an in-progress task that
		    // still has incomplete blockers is genuinely contradictory.
		    if (task.status === 'in_progress' && task.blockers.length > 0) {
		      rows.push({ level: 'warn', text: `Task ${task.id} is in progress but blocked by ${task.blockers.map((blocker) => blocker.id).join(', ')}.` })
		    }
		    if (task.status === 'in_progress' && task.owners.length === 0) {
		      rows.push({ level: 'warn', text: `Task ${task.id} is in progress with no declared owner.` })
		    }
		  }
		  if (team !== undefined && team.members !== undefined) {
		    for (const member of team.members) {
		      if (member.phase === 'failed') rows.push({ level: 'err', text: `Team member ${member.name} failed to provision${member.error === undefined ? '' : `: ${member.error}`}.` })
		    }
		    if (team.failure !== undefined) rows.push({ level: 'err', text: `Team projection reports a failure: ${team.failure}` })
		  }
		  return rows
		}
		
		/**
		 * Merge the declared roster with live team state.
		 *
		 * The point of the merge is to answer "is the plan running?" — so an agent with
		 * a live teammate shows the teammate's real status, an agent with no live
		 * counterpart is plainly marked as not created, and a live member the manifest
		 * never anticipated still appears (a roster that hides unknown members would
		 * be lying about what is running).
		 *
		 * @param index the host's project index.
		 * @param team live team projection, or undefined when no session is open.
		 * @returns `{ rows, live, declared, unplanned }`.
		 */
		function mergeAgents(index, team) {
		  const members = team?.members ?? []
		  const memberByName = new Map(members.map((member) => [member.name, member]))
		  const rows = index.agents.map((agent) => {
		    const member = memberByName.get(agent.id)
		    return {
		      ...agent,
		      live: member,
		      liveStatus: member === undefined ? 'not-created' : member.phase === 'active' ? 'active' : member.phase,
		      discrepancy: member !== undefined && member.phase === 'failed',
		    }
		  })
		  const planned = new Set(index.agents.map((agent) => agent.id))
		  const unplanned = members.filter((member) => member.role === 'teammate' && !planned.has(member.name))
		  const live = rows.filter((row) => row.liveStatus === 'active').length
		  const failed = rows.filter((row) => row.liveStatus === 'failed').length
		  const idle = rows.filter((row) => row.liveStatus === 'inactive').length
		  return {
		    rows,
		    live: members.filter((member) => member.role === 'teammate').length,
		    active: live,
		    idle,
		    failed,
		    declared: index.agents.length,
		    /** Planned agents that do not exist in the live team yet. */
		    notCreated: rows.filter((row) => row.liveStatus === 'not-created').length,
		    unplanned,
		  }
		}
		
		/**
		 * Where the declared plan and the live board agree, and where they do not.
		 *
		 * The manifest describes intended work; the team task board is what is actually
		 * happening. Matching them on subject text is the only honest join available —
		 * ids are independent — so this reports an unmatched count rather than
		 * pretending every task lines up.
		 * @param index the host's project index.
		 * @param team live team projection.
		 * @returns `{ liveTasks, matched, liveOnly, planOnly }`.
		 */
		function mergeTasks(index, team) {
		  const liveTasks = team?.tasks ?? []
		  const key = (subject) => String(subject ?? '').trim().toLowerCase().replace(/\s+/gu, ' ')
		  const liveBySubject = new Map(liveTasks.map((task) => [key(task.subject), task]))
		  const matched = []
		  const planOnly = []
		  for (const task of index.tasks) {
		    const live = liveBySubject.get(key(task.subject))
		    if (live === undefined) planOnly.push(task)
		    else matched.push({ planned: task, live })
		  }
		  const plannedKeys = new Set(index.tasks.map((task) => key(task.subject)))
		  return {
		    liveTasks,
		    matched,
		    planOnly,
		    liveOnly: liveTasks.filter((task) => !plannedKeys.has(key(task.subject))),
		  }
		}
		
		/**
		 * The agents that will be handed a given file, keyed both ways.
		 *
		 * @param index the host's project index.
		 * @returns `{ byFile, byComponent }` where `byFile` maps a path to the agents
		 *   that read or write it, and `byComponent` maps a component id to its files.
		 */
		function fileOwnership(index) {
		  const byFile = new Map()
		  for (const file of index.files) {
		    for (const agentId of file.agents) {
		      const entry = byFile.get(file.path) ?? new Set()
		      entry.add(agentId)
		      byFile.set(file.path, entry)
		    }
		  }
		  const byComponent = new Map()
		  for (const component of index.components) {
		    const paths = new Set()
		    for (const entry of [...component.paths, ...component.docs, ...component.decisions]) {
		      if (entry.status === 'missing') continue
		      if (entry.exact) paths.add(entry.path)
		      for (const sample of entry.sample) paths.add(sample)
		    }
		    byComponent.set(component.id, paths)
		  }
		  return { byFile, byComponent }
		}
		
		/**
		 * Group a flat file list into a collapsible directory tree.
		 *
		 * @param files file rows carrying `path`.
		 * @param options `{ maxDepth }`.
		 * @returns root nodes `{ name, path, dir, children, file }`.
		 */
		function buildFileTree(files, options = {}) {
		  const maxDepth = options.maxDepth ?? 4
		  const root = { name: '', path: '', dir: true, children: new Map() }
		  for (const file of files) {
		    const parts = String(file.path).split('/')
		    if (parts.length > maxDepth + 1) continue
		    let node = root
		    for (let index = 0; index < parts.length; index += 1) {
		      const name = parts[index]
		      const isLeaf = index === parts.length - 1
		      const path = parts.slice(0, index + 1).join('/')
		      let child = node.children.get(name)
		      if (child === undefined) {
		        child = { name, path, dir: !isLeaf, children: new Map(), file: isLeaf ? file : undefined, size: 0 }
		        node.children.set(name, child)
		      }
		      if (isLeaf) child.file = file
		      child.size += file.size ?? 0
		      node = child
		    }
		  }
		  /** Collapse the map form into sorted arrays. */
		  const finalize = (node) => ({
		    name: node.name,
		    path: node.path,
		    dir: node.dir,
		    file: node.file,
		    size: node.size,
		    children: [...node.children.values()]
		      .sort((left, right) => (left.dir === right.dir ? (left.name < right.name ? -1 : 1) : left.dir ? -1 : 1))
		      .map(finalize),
		  })
		  return finalize(root).children
		}
		
		/**
		 * Render a byte count the way a file manager does.
		 * @param bytes size in bytes.
		 * @returns a short human-readable size.
		 */
		function formatBytes(bytes) {
		  const value = Number(bytes) || 0
		  if (value < 1024) return `${value} B`
		  if (value < 1024 * 1024) return `${(value / 1024).toFixed(1)} KB`
		  return `${(value / (1024 * 1024)).toFixed(1)} MB`
		}
		
		/**
		 * Which root session's team the panel should show.
		 *
		 * The cockpit is not itself a session, so it has to pick: the session the user
		 * is actually looking at, identified by the shell's retention counter, falling
		 * back to the newest root session. Subagent sessions are skipped — their team
		 * belongs to their Lead.
		 *
		 * @param sessionsSnapshot the client `sessions` list snapshot.
		 * @returns a session id, or undefined.
		 */
		function pickLeadSession(sessionsSnapshot) {
		  const byId = sessionsSnapshot?.byId
		  if (byId === undefined || byId === null) return undefined
		  const ids = sessionsSnapshot.ids ?? Object.keys(byId)
		  const roots = ids.map((id) => byId[id]).filter((row) => row !== undefined && row !== null && row.subagent === undefined)
		  const retained = roots.filter((row) => (row.retainedBy?.mainView ?? 0) > 0)
		  return retained[0]?.sessionId ?? roots[0]?.sessionId ?? ids[0]
		}
		
		/**
		 * A stable key for a list of sessions, so effects can depend on identity
		 * without depending on object identity (which changes on every mutation).
		 * @param sessionsSnapshot the client `sessions` list snapshot.
		 * @returns a comparable string.
		 */
		function sessionsKey(sessionsSnapshot) {
		  const ids = sessionsSnapshot?.ids ?? []
		  return ids.join('|')
		}
		
		// ---- lib/client/index.js ----
		var React = require("react");
		/**
		 * Project Cockpit — the browser half.
		 *
		 * Registers two seats in the shell:
		 *   - a `sidebar.panellist` glyph, which is the toolbar button's icon;
		 *   - a keyed `main` panel, which is the full-width page the button opens.
		 *
		 * The panel reads the project index from the host half over `/api/project-cockpit`
		 * (authenticated by the shell's browser session like every other `/api` route)
		 * and the live team roster from the session projections the Agent Teams plugin
		 * already publishes. It writes nothing anywhere.
		 */
		
		/* import react */
		/* inlined ./styles.js */
		/* inlined ./viewmodel.js */
		const NS = 'project-cockpit'
		const PANEL_ID = 'project-cockpit'
		const API = 'api/project-cockpit'
		
		/** The panel's identity in the sidebar toolbar. */
		const name = PANEL_ID
		
		/** Services the client half needs: the slot registry and the session store. */
		const inject = ['slots', 'sessions']
		
		const h = React.createElement
		
		// ---------------------------------------------------------------------------
		// styles
		// ---------------------------------------------------------------------------
		
		/** Install the stylesheet once per page. */
		function installStyles() {
		  const tagId = `${NS}/cockpit`
		  if (document.querySelector(`style[data-plugin-css="${tagId}"]`) !== null) return
		  const tag = document.createElement('style')
		  tag.dataset.plugin = NS
		  tag.dataset.pluginCss = tagId
		  tag.textContent = cockpitCss()
		  document.head.appendChild(tag)
		}
		
		// ---------------------------------------------------------------------------
		// data
		// ---------------------------------------------------------------------------
		
		/**
		 * Subscribe to a plain snapshot store (`{ getSnapshot, subscribe }`) without
		 * needing a store instance of our own.
		 * @param source the store, or undefined when the service is absent.
		 * @returns the current value, re-rendering on change.
		 */
		function useSnapshot(source) {
		  const subscribe = React.useCallback(
		    (onChange) => {
		      if (source === undefined || source === null || typeof source.subscribe !== 'function') return () => {}
		      return source.subscribe(onChange)
		    },
		    [source],
		  )
		  const getSnapshot = React.useCallback(() => {
		    if (source === undefined || source === null || typeof source.getSnapshot !== 'function') return undefined
		    return source.getSnapshot()
		  }, [source])
		  return React.useSyncExternalStore(subscribe, getSnapshot, getSnapshot)
		}
		
		/** Fetch one shape from the host's cockpit route. */
		async function fetchCockpit(view, signal, sessionId) {
		  const url = new URL(API, window.location.href)
		  if (view !== undefined) url.searchParams.set('view', view)
		  // Name the session whose project this is. The panel is mounted once for the
		  // whole shell, so without this the host can only guess at which project the
		  // reader means — and with the cockpit usable on any project, a guess is a bug.
		  if (typeof sessionId === 'string' && sessionId !== '') url.searchParams.set('session', sessionId)
		  const response = await fetch(url, { signal, headers: { accept: 'application/json' } })
		  if (!response.ok) throw new Error(`cockpit request failed: HTTP ${response.status}`)
		  const payload = await response.json()
		  if (payload !== null && typeof payload === 'object' && typeof payload.error === 'string') throw new Error(payload.error)
		  return payload
		}
		
		/**
		 * Post one planning action.
		 *
		 * Read failures and action failures are separated on purpose: a read that fails
		 * means the panel has nothing to draw, an action that fails is a sentence to
		 * show beside the button that caused it. The host's reason is surfaced verbatim
		 * — a 409 from a stale revision is information, not an error to swallow.
		 *
		 * @param action the action name.
		 * @param payload its arguments.
		 * @param sessionId the session whose team is being changed.
		 * @returns the host's result.
		 * @throws Error carrying the host's reason.
		 */
		async function postAction(action, payload, sessionId) {
		  const response = await fetch(new URL(API, window.location.href), {
		    method: 'POST',
		    headers: { 'content-type': 'application/json' },
		    body: JSON.stringify({ action, sessionId, payload }),
		  })
		  const body = await response.json().catch(() => ({}))
		  if (!response.ok) throw new Error(typeof body.error === 'string' ? body.error : `HTTP ${response.status}`)
		  return body
		}
		
		/**
		 * The panel's data: the project index from the host, plus the live team state
		 * from this session's projections.
		 * @param sessions the client sessions service.
		 * @returns `{ index, team, loading, error, reload }`.
		 */
		function useCockpit(sessions) {
		  const [index, setIndex] = React.useState(null)
		  const [error, setError] = React.useState(null)
		  const [loading, setLoading] = React.useState(true)
		  const [nonce, setNonce] = React.useState(0)
		  // The board read straight from the team service. It carries each task's
		  // revision, which the projection does not — and an action needs the revision
		  // to be a compare-and-set rather than a blind overwrite.
		  const [board, setBoard] = React.useState(null)
		  const [boardError, setBoardError] = React.useState(null)
		  // What the running host half says it can do. The two halves can be at
		  // different revisions, so the panel asks rather than assuming.
		  const [capabilities, setCapabilities] = React.useState(null)
		  // Which directory the host actually read, and which rule chose it. Shown in
		  // the footer, because "which project am I looking at" must never be a guess.
		  const [resolvedRoot, setResolvedRoot] = React.useState(null)
		  const [rootSource, setRootSource] = React.useState(null)
		
		  // Which session's project to show. Resolved before the fetch so the request
		  // can name it: the host must not have to guess which project the reader means.
		  const list = useSnapshot(sessions?.list)
		  const sessionId = pickLeadSession(list)
		  const snapshotKey = sessionsKey(list)
		
		  React.useEffect(() => {
		    const controller = new AbortController()
		    let live = true
		    setLoading(true)
		    fetchCockpit('index', controller.signal, sessionId)
		      .then((payload) => {
		        if (!live) return
		        setIndex(payload.index)
		        setCapabilities(payload.capabilities ?? null)
		        setResolvedRoot(payload.root ?? null)
		        setRootSource(payload.rootSource ?? null)
		        setError(null)
		      })
		      .catch((reason) => {
		        if (!live || controller.signal.aborted) return
		        setError(reason instanceof Error ? reason.message : String(reason))
		      })
		      .finally(() => {
		        if (live) setLoading(false)
		      })
		    return () => {
		      live = false
		      controller.abort()
		    }
		  }, [nonce, sessionId])
		
		  const projections = list?.projectionsBySession
		  const team = sessionId === undefined ? undefined : projections?.[sessionId]?.values?.agentTeam
		
		  // Only ask the service for the board when a session is open; the answer is
		  // "no team" otherwise and the request would be noise.
		  React.useEffect(() => {
		    if (sessionId === undefined) {
		      setBoard(null)
		      setBoardError(null)
		      return undefined
		    }
		    let live = true
		    postAction('read_team', {}, sessionId)
		      .then((payload) => {
		        if (!live) return
		        setBoard({ members: payload.members ?? [], tasks: payload.tasks ?? [] })
		        setBoardError(null)
		      })
		      .catch((reason) => {
		        if (!live) return
		        setBoard(null)
		        setBoardError(reason instanceof Error ? reason.message : String(reason))
		      })
		    return () => {
		      live = false
		    }
		  }, [sessionId, nonce, snapshotKey])
		
		  const reload = React.useCallback(() => setNonce((value) => value + 1), [])
		  return { index, team, board, boardError, capabilities, loading, error, reload, sessionId, snapshotKey, resolvedRoot, rootSource }
		}
		
		// ---------------------------------------------------------------------------
		// small building blocks
		// ---------------------------------------------------------------------------
		
		/** A coloured dot + status word. */
		function StatusPill({ status, label }) {
		  return h(
		    'span',
		    { className: CLASS.badge },
		    h('span', { className: CLASS.dot, style: { background: statusColor(status) } }),
		    label ?? statusLabel(status),
		  )
		}
		
		/** A row of KPI figures. */
		function KpiRow({ rows }) {
		  return h(
		    'div',
		    { className: CLASS.kpi },
		    rows.map((row) =>
		      h(
		        'div',
		        { key: row.label },
		        h('div', { className: CLASS.kpiValue }, row.value),
		        h('div', { className: CLASS.kpiLabel }, row.label),
		        row.hint === undefined ? null : h('div', { className: `${CLASS.muted} ${CLASS.mono}` }, row.hint),
		      ),
		    ),
		  )
		}
		
		/** A labelled file path with a present/absent marker. */
		function PathChip({ entry, access }) {
		  const status = entry.status
		  const color = status === 'missing' ? 'var(--pcx-err)' : access === 'write' ? 'var(--pcx-brand)' : 'var(--pcx-ok)'
		  const title = status === 'missing'
		    ? `${entry.path} — declared but not on disk`
		    : status === 'directory'
		      ? `${entry.path} — directory, ${entry.matches} file(s)`
		      : `${entry.path} — file`
		  return h(
		    'span',
		    { className: CLASS.badge, title, style: { borderColor: color } },
		    h('span', { className: CLASS.dot, style: { background: color } }),
		    h('span', { className: CLASS.mono }, entry.path),
		    status === 'directory' && entry.matches > 0 ? h('span', { className: CLASS.muted }, `(${entry.matches})`) : null,
		    access === 'write' ? h('span', { className: CLASS.tag }, 'write') : null,
		  )
		}
		
		/** A collapsible block, closed by default so the page stays scannable. */
		function Collapsible({ summary, children, open }) {
		  return h(
		    'details',
		    { className: CLASS.details, open: open === true },
		    h('summary', { className: CLASS.summary }, summary),
		    h('div', { style: { marginTop: '8px' } }, children),
		  )
		}
		
		/**
		 * A button that performs one planning action and reports its own outcome.
		 *
		 * The result stays beside the button that caused it rather than in a page-wide
		 * banner, because "the task was created" and "the revision was stale" are
		 * answers about *that* row. The button disables itself while the request is in
		 * flight so a double-click cannot post twice.
		 *
		 * @param props `{ label, title, run, onDone, disabled }` where `run` performs
		 *   the action and `onDone` refreshes whatever the action changed.
		 */
		function ActionButton({ label, title, run, onDone, disabled }) {
		  const [state, setState] = React.useState({ phase: 'idle', message: '' })
		  const click = React.useCallback(() => {
		    setState({ phase: 'running', message: '' })
		    Promise.resolve()
		      .then(run)
		      .then((result) => {
		        setState({ phase: 'done', message: typeof result === 'string' ? result : 'Done.' })
		        if (onDone !== undefined) onDone()
		      })
		      .catch((reason) => {
		        setState({ phase: 'error', message: reason instanceof Error ? reason.message : String(reason) })
		      })
		  }, [run, onDone])
		
		  return h(
		    'span',
		    { style: { display: 'inline-flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' } },
		    h(
		      'button',
		      {
		        type: 'button',
		        className: CLASS.button,
		        title,
		        disabled: disabled === true || state.phase === 'running',
		        onClick: click,
		      },
		      state.phase === 'running' ? 'Working…' : label,
		    ),
		    state.phase === 'idle'
		      ? null
		      : h(
		          'span',
		          { className: state.phase === 'error' ? CLASS.err : CLASS.ok, style: { fontSize: '11.5px' } },
		          state.message,
		        ),
		  )
		}
		
		/** The empty / error / loading states, kept in one place so they read alike. */
		function Empty({ children }) {
		  return h('div', { className: CLASS.empty }, children)
		}
		
		// ---------------------------------------------------------------------------
		// the sidebar glyph
		// ---------------------------------------------------------------------------
		
		/**
		 * The toolbar icon: a small architecture map — two inputs feeding one node,
		 * that node feeding two outputs — drawn in the sidebar's own cell.
		 * @param props `{ size, active }` supplied by the sidebar.
		 */
		function CockpitGlyph({ size = 16, active = false }) {
		  const stroke = 'currentColor'
		  return h(
		    'svg',
		    {
		      width: size,
		      height: size,
		      viewBox: '0 0 16 16',
		      fill: 'none',
		      'aria-hidden': 'true',
		      style: { display: 'block', opacity: active ? 1 : 0.85 },
		    },
		    h('path', {
		      d: 'M2.2 2.6h2.6M2.2 13.4h2.6M11.2 5.4h2.6M11.2 10.6h2.6',
		      stroke,
		      strokeWidth: '1.3',
		      strokeLinecap: 'round',
		    }),
		    h('rect', { x: '5.4', y: '5.4', width: '5.2', height: '5.2', rx: '1.3', stroke, strokeWidth: '1.3' }),
		    h('path', {
		      d: 'M4.8 2.6c1.6 0 1.8 3.6 1.8 4.4M4.8 13.4c1.6 0 1.8-3.6 1.8-4.4M11.2 5.4c-1.6 0-1.8 1.2-1.8 2M11.2 10.6c-1.6 0-1.8-1.2-1.8-2',
		      stroke,
		      strokeWidth: '1.1',
		      strokeLinecap: 'round',
		      opacity: '0.75',
		    }),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// Architecture
		// ---------------------------------------------------------------------------
		
		/** One component in the architecture map. */
		function ComponentNode({ component, selected, onSelect }) {
		  return h(
		    'button',
		    {
		      type: 'button',
		      className: selected ? `${CLASS.node} ${CLASS.nodeActive}` : CLASS.node,
		      style: { borderLeftColor: statusColor(component.status) },
		      onClick: () => onSelect(component.id),
		      title: component.summary === '' ? component.name : component.summary,
		    },
		    h(
		      'span',
		      { className: CLASS.nodeTop },
		      h('span', { className: CLASS.nodeName }, component.name),
		      h(StatusPill, { status: component.status }),
		    ),
		    h(
		      'span',
		      { className: CLASS.nodeKind },
		      [component.kind, component.language, component.status === 'cut' ? 'cut' : null].filter(Boolean).join(' · '),
		    ),
		    component.dependsOn.length === 0
		      ? h('span', { className: CLASS.nodeDeps }, 'no dependencies')
		      : h('span', { className: CLASS.nodeDeps }, `← ${component.dependsOn.join(', ')}`),
		    component.missingPaths > 0
		      ? h('span', { className: `${CLASS.nodeDeps} ${CLASS.warn}` }, `${component.missingPaths} declared path(s) absent`)
		      : null,
		  )
		}
		
		/** The architecture tab. */
		function ArchitectureView({ index, selected, onSelect }) {
		  const { segments, total } = statusBreakdown(index.components)
		  const groups = groupByLayer(index.components, index.layers)
		  const component = index.components.find((candidate) => candidate.id === selected)
		
		  return h(
		    'div',
		    { className: CLASS.view },
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Build state'),
		      h(KpiRow, { rows: kpis(index) }),
		      h(
		        'div',
		        { style: { marginTop: '14px' } },
		        h(
		          'div',
		          { className: CLASS.bar, role: 'img', 'aria-label': 'component status distribution' },
		          segments.map((segment) =>
		            h('div', { key: segment.status, className: CLASS.barSeg, style: { background: segment.color, flexGrow: segment.count } }),
		          ),
		        ),
		        h(
		          'div',
		          { className: CLASS.legend },
		          segments.map((segment) =>
		            h(
		              'span',
		              { key: segment.status, className: CLASS.legendItem },
		              h('span', { className: CLASS.swatch, style: { background: segment.color } }),
		              `${segment.count} ${segment.label}`,
		            ),
		          ),
		          total === 0 ? h('span', { className: CLASS.muted }, 'no components declared') : null,
		        ),
		      ),
		    ),
		
		    component === undefined
		      ? null
		      : h(ComponentDetail, { component, onSelect }),
		
		    groups.length === 0
		      ? h(Empty, null, 'No components are declared yet. Add them to the manifest and they appear here as a build-order map.')
		      : groups.map((group) =>
		          h(
		            'section',
		            { key: group.layer, className: CLASS.layer },
		            h(
		              'div',
		              { className: CLASS.layerHead },
		              h('span', { className: CLASS.layerName }, group.layer),
		              h('span', { className: CLASS.layerRule }),
		              h('span', { className: CLASS.muted }, `${group.components.length}`),
		            ),
		            h(
		              'div',
		              { className: CLASS.nodes },
		              group.components.map((entry) =>
		                h(ComponentNode, { key: entry.id, component: entry, selected: entry.id === selected, onSelect }),
		              ),
		            ),
		          ),
		        ),
		
		    index.invariants.length === 0
		      ? null
		      : h(
		          'section',
		          { className: CLASS.section },
		          h('h2', { className: CLASS.sectionTitle }, 'Invariants'),
		          index.invariants.map((invariant) =>
		            h(
		              'div',
		              { key: invariant.id, className: CLASS.inv },
		              h('span', { className: CLASS.invId }, invariant.id),
		              h(
		                'span',
		                null,
		                invariant.statement,
		                invariant.record === '' ? null : h('span', { className: `${CLASS.muted} ${CLASS.mono}` }, ` · ${invariant.record}`),
		              ),
		            ),
		          ),
		        ),
		  )
		}
		
		/** The expanded detail for one selected component. */
		function ComponentDetail({ component, onSelect }) {
		  const declared = [
		    ...component.paths.map((entry) => ({ entry, access: 'own' })),
		    ...component.docs.map((entry) => ({ entry, access: 'doc' })),
		    ...component.decisions.map((entry) => ({ entry, access: 'adr' })),
		  ]
		  return h(
		    'section',
		    { className: CLASS.section },
		    h(
		      'div',
		      { className: CLASS.cardHeader },
		      h('h2', { className: CLASS.heading }, component.name),
		      h(StatusPill, { status: component.status }),
		      h('span', { className: `${CLASS.muted} ${CLASS.mono}` }, component.id),
		      h('span', { style: { flex: 1 } }),
		      h('button', { type: 'button', className: CLASS.button, onClick: () => onSelect(undefined) }, 'Close'),
		    ),
		    component.summary === '' ? null : h('p', { className: CLASS.cardMeta }, component.summary),
		    h(
		      'div',
		      { className: CLASS.cols, style: { marginTop: '12px' } },
		      h(
		        'div',
		        { className: CLASS.col },
		        h('div', { className: CLASS.headingL2 }, `Declared paths (${declared.length})`),
		        declared.length === 0
		          ? h('span', { className: CLASS.muted }, 'none declared')
		          : h(
		              'div',
		              { className: CLASS.deps },
		              declared.map(({ entry, access }) => h(PathChip, { key: `${access}:${entry.path}`, entry, access: access === 'own' ? undefined : access })),
		            ),
		      ),
		      h(
		        'div',
		        { className: CLASS.col },
		        h('div', { className: CLASS.headingL2 }, 'Relationships'),
		        h(
		          'div',
		          { className: CLASS.list },
		          h(
		            'div',
		            { className: CLASS.listItem },
		            h('span', { className: CLASS.muted }, 'depends on'),
		            component.dependsOn.length === 0
		              ? h('span', { className: CLASS.muted }, '—')
		              : component.dependsOn.map((id) => h('span', { key: id, className: CLASS.dep }, id)),
		          ),
		          h(
		            'div',
		            { className: CLASS.listItem },
		            h('span', { className: CLASS.muted }, 'depended on by'),
		            component.dependents.length === 0
		              ? h('span', { className: CLASS.muted }, '—')
		              : component.dependents.map((id) => h('span', { key: id, className: CLASS.dep }, id)),
		          ),
		          h('div', { className: CLASS.listItem }, h('span', { className: CLASS.muted }, 'files on disk'), h('span', null, `${component.fileCount}`)),
		        ),
		        component.notes === '' ? null : h('p', { className: CLASS.cardMeta }, component.notes),
		      ),
		    ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// Agents
		// ---------------------------------------------------------------------------
		
		/** One agent card: its job, its files, and whether it exists yet. */
		function AgentCard({ row, expanded, onToggle, actions }) {
		  const color = row.liveStatus === 'not-created' ? 'var(--pcx-idle)' : statusColor(row.liveStatus)
		  return h(
		    'div',
		    { className: CLASS.card, style: { borderLeft: `3px solid ${color}` } },
		    h(
		      'button',
		      { type: 'button', className: CLASS.agentRow, onClick: () => onToggle(row.id), 'aria-expanded': expanded },
		      h('span', { className: CLASS.emoji }, row.emoji === '' ? '🤖' : row.emoji),
		      h(
		        'span',
		        { style: { flex: 1, minWidth: 0 } },
		        h('span', { className: CLASS.agentName }, row.id),
		        h('span', { className: CLASS.agentRole }, ` · ${row.role}`),
		        h('div', { className: CLASS.cardMeta }, row.purpose === '' ? 'no purpose declared' : row.purpose),
		      ),
		      h(StatusPill, { status: row.liveStatus, label: row.liveStatus === 'not-created' ? 'not created' : statusLabel(row.liveStatus) }),
		    ),
		
		    h(
		      'div',
		      { style: { marginTop: '9px' } },
		      h('div', { className: CLASS.headingL2 }, 'Task'),
		      h(
		        'div',
		        { className: CLASS.taskBody },
		        row.task === undefined
		          ? row.task === undefined && row.notes === ''
		            ? h('span', { className: CLASS.muted }, 'No task declared for this agent.')
		            : row.notes
		          : h(
		              'span',
		              null,
		              h('strong', null, row.task.subject),
		              ' ',
		              h(StatusPill, { status: row.task.status }),
		              row.task.blocked ? h('span', { className: CLASS.warn }, ' · blocked') : null,
		            ),
		      ),
		    ),
		
		    h(
		      'div',
		      { style: { marginTop: '9px' } },
		      h('div', { className: CLASS.headingL2 }, `Files provided (${row.providedFiles.length})`),
		      row.providedFiles.length === 0
		        ? h('span', { className: CLASS.muted }, 'This agent is handed no files.')
		        : h(
		            'div',
		            { className: CLASS.deps },
		            (expanded ? row.providedFiles : row.providedFiles.slice(0, 6)).map((entry) =>
		              h(PathChip, { key: `${entry.access}:${entry.path}`, entry, access: entry.access }),
		            ),
		            !expanded && row.providedFiles.length > 6
		              ? h('span', { className: CLASS.muted }, `+${row.providedFiles.length - 6} more`)
		              : null,
		          ),
		      row.missingProvided > 0 ? h('div', { className: `${CLASS.warn} ${CLASS.mono}`, style: { marginTop: '6px' } }, `${row.missingProvided} declared path(s) are not on disk`) : null,
		    ),
		
		    actions === undefined || actions.sendTask === undefined
		      ? null
		      : h('div', { style: { marginTop: '9px' } }, actions.sendTask(row)),
		  )
		}
		
		/** The agents tab: the planned roster against the live team. */
		function AgentsView({ index, team, expanded, onToggle, actions }) {
		  const merged = mergeAgents(index, team)
		  return h(
		    'div',
		    { className: CLASS.view },
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Roster'),
		      h(KpiRow, {
		        rows: [
		          { label: 'planned agents', value: `${merged.declared}` },
		          { label: 'live teammates', value: `${merged.live}` },
		          { label: 'active now', value: `${merged.active}`, hint: team === undefined ? 'no session' : undefined },
		          { label: 'inactive', value: `${merged.idle}` },
		          { label: 'not created yet', value: `${merged.notCreated}` },
		          ...(merged.failed > 0 ? [{ label: 'failed', value: `${merged.failed}` }] : []),
		        ],
		      }),
		      team === undefined
		        ? h('p', { className: CLASS.cardMeta }, 'No Agent Team is open in this session, so live status is unknown. The roster below is the declared plan.')
		        : null,
		      merged.unplanned.length === 0
		        ? null
		        : h(
		            'div',
		            { style: { marginTop: '12px' } },
		            h('div', { className: CLASS.headingL2 }, 'Live members the manifest does not declare'),
		            h(
		              'div',
		              { className: CLASS.list },
		              merged.unplanned.map((member) =>
		                h(
		                  'div',
		                  { key: member.id, className: CLASS.listItem },
		                  h(StatusPill, { status: member.phase }),
		                  h('span', { className: CLASS.mono }, member.name),
		                  h('span', { className: CLASS.muted }, member.error ?? ''),
		                ),
		              ),
		            ),
		          ),
		    ),
		
		    index.agents.length === 0
		      ? h(Empty, null, 'No agents are declared. Add an "agents" array to the manifest to plan the roster — each agent pairs a task with the exact files it will be handed.')
		      : h(
		          'div',
		          { className: CLASS.grid },
		          index.agents.map((agent) => {
		            const row = merged.rows.find((candidate) => candidate.id === agent.id) ?? agent
		            return h(AgentCard, { key: agent.id, row, expanded: expanded.has(agent.id), onToggle, actions })
		          }),
		        ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// Tasks
		// ---------------------------------------------------------------------------
		
		/**
		 * The board action for one planned task.
		 *
		 * Three outcomes, and the difference between them matters to the reader:
		 * there is no board to add to; the task is already on it (shown with its live
		 * revision, because the revision is what a later change must quote); or it can
		 * be created now. Matching is by subject text — the only join available between
		 * the manifest's ids and the board's — so an unmatched task is offered rather
		 * than assumed absent.
		 *
		 * @param props `{ task, board, sessionId, onDone }`.
		 */
		function TaskBoardAction({ task, board, sessionId, supported, onDone }) {
		  if (supported === false) {
		    return h(
		      'div',
		      { className: `${CLASS.warn} ${CLASS.mono}`, style: { marginTop: '4px' } },
		      'Creating tasks needs the host half of the cockpit to be restarted.',
		    )
		  }
		  if (sessionId === undefined || sessionId === '') {
		    return h('div', { className: `${CLASS.muted} ${CLASS.mono}`, style: { marginTop: '4px' } }, 'No open session, so no board to plan onto.')
		  }
		  if (board === null) {
		    return h('div', { className: `${CLASS.muted} ${CLASS.mono}`, style: { marginTop: '4px' } }, 'No live board in this session.')
		  }
		  const norm = (value) => String(value ?? '').trim().toLowerCase().replace(/\s+/gu, ' ')
		  const existing = board.tasks.find((entry) => norm(entry.subject) === norm(task.subject))
		  if (existing !== undefined) {
		    return h(
		      'div',
		      { className: `${CLASS.ok} ${CLASS.mono}`, style: { marginTop: '4px' } },
		      `On the board as ${existing.id} · revision ${existing.revision} · ${existing.status}`,
		    )
		  }
		  return h(
		    'div',
		    { style: { marginTop: '4px' } },
		    h(ActionButton, {
		      label: 'Add to team board',
		      title: 'Create this task on the shared team task board',
		      run: async () => {
		        const result = await postAction(
		          'create_task',
		          {
		            subject: task.subject,
		            description: task.description === '' ? task.subject : task.description,
		            writeScopes: task.writeScopes,
		          },
		          sessionId,
		        )
		        return `Created ${result.task?.id ?? 'the task'} on the board.`
		      },
		      onDone,
		    }),
		  )
		}
		
		/** The tasks tab: the written plan against the live board. */
		function TasksView({ index, team, board, boardError, actions }) {
		  const merged = mergeTasks(index, team)
		  const byStatus = (status) => index.tasks.filter((task) => task.status === status)
		  const groups = [
		    { status: 'in_progress', rows: byStatus('in_progress') },
		    { status: 'pending', rows: byStatus('pending') },
		    { status: 'blocked', rows: byStatus('blocked') },
		    { status: 'completed', rows: byStatus('completed') },
		  ].filter((group) => group.rows.length > 0)
		
		  return h(
		    'div',
		    { className: CLASS.view },
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Live board vs written plan'),
		      h(KpiRow, {
		        rows: [
		          { label: 'planned tasks', value: `${index.tasks.length}` },
		          { label: 'on the live board', value: `${merged.liveTasks.length}`, hint: team === undefined ? 'no session' : undefined },
		          { label: 'matched by subject', value: `${merged.matched.length}` },
		          { label: 'planned, not on board', value: `${merged.planOnly.length}` },
		          { label: 'on board, not planned', value: `${merged.liveOnly.length}` },
		        ],
		      }),
		      boardError === null
		        ? null
		        : h('div', { className: CLASS.warnBox, style: { marginTop: '10px' } }, `The shared board could not be read: ${boardError}`),
		      h(
		        'p',
		        { className: CLASS.cardMeta },
		        board === null
		          ? 'No live team board is available in this session, so nothing can be added to it from here.'
		          : `Board reachable · ${board.tasks.length} task(s) · ${board.members.length} member(s). A task is added with its compare-and-set revision, so two writers cannot overwrite each other.`,
		      ),
		      merged.liveOnly.length === 0
		        ? null
		        : h(
		            'div',
		            { style: { marginTop: '12px' } },
		            h('div', { className: CLASS.headingL2 }, 'Live tasks with no written counterpart'),
		            h(
		              'div',
		              { className: CLASS.list },
		              merged.liveOnly.map((task) =>
		                h(
		                  'div',
		                  { key: task.id, className: CLASS.listItem },
		                  h(StatusPill, { status: task.status }),
		                  h('span', { className: CLASS.mono }, task.id),
		                  h('span', { className: CLASS.cell }, task.subject),
		                  task.ownerName === undefined ? null : h('span', { className: CLASS.muted }, task.ownerName),
		                ),
		              ),
		            ),
		          ),
		    ),
		
		    groups.length === 0
		      ? h(Empty, null, 'No tasks are declared. Tasks give the cockpit its build order — add them with dependencies and write scopes.')
		      : groups.map((group) =>
		          h(
		            'section',
		            { key: group.status, className: CLASS.layer },
		            h(
		              'div',
		              { className: CLASS.layerHead },
		              h('span', { className: CLASS.layerName }, statusLabel(group.status)),
		              h('span', { className: CLASS.layerRule }),
		              h('span', { className: CLASS.muted }, `${group.rows.length}`),
		            ),
		            h(
		              'div',
		              { className: CLASS.grid },
		              group.rows.map((task) =>
		                h(
		                  'div',
		                  { key: task.id, className: CLASS.taskCard, style: { borderLeftColor: statusColor(task.status) } },
		                  h(
		                    'div',
		                    { className: CLASS.taskHead },
		                    h('span', { className: `${CLASS.mono}` }, task.id),
		                    h('strong', { style: { flex: 1, minWidth: 0 } }, task.subject),
		                    task.blocked ? h('span', { className: CLASS.badge }, h('span', { className: CLASS.dot, style: { background: 'var(--pcx-err)' } }), 'blocked') : null,
		                  ),
		                  task.description === '' ? null : h('div', { className: CLASS.taskBody }, task.description),
		                  h(
		                    'div',
		                    { className: CLASS.listItem },
		                    h('span', { className: CLASS.muted }, 'owner'),
		                    task.owners.length === 0 ? h('span', { className: CLASS.muted }, 'unassigned') : task.owners.map((id) => h('span', { key: id, className: CLASS.tag }, id)),
		                  ),
		                  task.blockers.length > 0
		                    ? h(
		                        'div',
		                        { className: CLASS.listItem },
		                        h('span', { className: CLASS.muted }, 'waiting on'),
		                        task.blockers.map((blocker) => h('span', { key: blocker.id, className: CLASS.dep }, `${blocker.id} ${blocker.status}`)),
		                      )
		                    : null,
		                  task.writeScopes.length === 0
		                    ? null
		                    : h(
		                        'div',
		                        { className: CLASS.deps },
		                        task.scopeStatus.map((entry) => h(PathChip, { key: entry.path, entry, access: 'write' })),
		                      ),
		                  h(TaskBoardAction, { task, board, sessionId: actions === undefined ? undefined : actions.sessionId, supported: actions === undefined ? undefined : actions.supported, onDone: actions === undefined ? undefined : actions.onDone }),
		                ),
		              ),
		            ),
		          ),
		        ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// Files
		// ---------------------------------------------------------------------------
		
		/** One directory level of the workspace tree. */
		function TreeNode({ node, depth, ownership, expanded, onToggle }) {
		  if (!node.dir) {
		    const agents = ownership.byFile.get(node.path)
		    return h(
		      'div',
		      { className: CLASS.treeRow, style: { paddingLeft: `${6 + depth * 14}px` } },
		      h('span', { className: CLASS.treeName, title: node.path }, node.name),
		      agents === undefined ? null : [...agents].map((id) => h('span', { key: id, className: CLASS.tag }, id)),
		      h('span', { className: CLASS.treeMeta }, formatBytes(node.size)),
		      h('span', { className: CLASS.fileType, style: { display: 'none' } }),
		    )
		  }
		  const open = expanded.has(node.path)
		  return h(
		    'div',
		    null,
		    h(
		      'button',
		      {
		        type: 'button',
		        className: CLASS.treeRow,
		        style: { paddingLeft: `${6 + depth * 14}px`, border: 0, background: 'transparent', width: '100%', cursor: 'pointer', color: 'inherit', textAlign: 'left' },
		        onClick: () => onToggle(node.path),
		      },
		      h('span', { className: CLASS.treeMeta }, open ? '▾' : '▸'),
		      h('span', { className: CLASS.treeName }, node.name),
		      h('span', { className: CLASS.treeMeta }, `${node.children.length}`),
		    ),
		    open ? node.children.map((child) => h(TreeNode, { key: child.path, node: child, depth: depth + 1, ownership, expanded, onToggle })) : null,
		  )
		}
		
		/** The files tab: the real tree, the agent↔file join, and the unclaimed set. */
		function FilesView({ index, expandedTree, onToggleTree, focusAgent }) {
		  const ownership = { byFile: new Map() }
		  for (const file of index.files) ownership.byFile.set(file.path, new Set(file.agents))
		  const tree = buildFileTree(index.files, { maxDepth: 5 })
		  const agents = focusAgent === undefined || focusAgent === '' ? index.agents : index.agents.filter((agent) => agent.id === focusAgent)
		  const agentPaths = new Set()
		  for (const agent of agents) for (const entry of agent.providedFiles) agentPaths.add(entry.path)
		  const providedFiles = index.files.filter((file) => agentPaths.has(file.path) || [...(ownership.byFile.get(file.path) ?? [])].some((id) => agents.some((agent) => agent.id === id)))
		
		  return h(
		    'div',
		    { className: CLASS.view },
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Which files each agent is handed'),
		      h(
		        'div',
		        { className: CLASS.table },
		        h(
		          'div',
		          { className: `${CLASS.row} ${CLASS.muted}` },
		          h('span', { className: CLASS.cell, style: { width: '120px', flex: 'none' } }, 'agent'),
		          h('span', { className: CLASS.cell, style: { width: '90px', flex: 'none' } }, 'state'),
		          h('span', { className: CLASS.cell, style: { width: '70px', flex: 'none' } }, 'read'),
		          h('span', { className: CLASS.cell, style: { width: '70px', flex: 'none' } }, 'write'),
		          h('span', { className: CLASS.cell }, 'task'),
		        ),
		        index.agents.length === 0
		          ? h('div', { className: CLASS.muted }, 'No agents declared.')
		          : index.agents.map((agent) =>
		              h(
		                'div',
		                { key: agent.id, className: CLASS.row },
		                h('span', { className: `${CLASS.cell} ${CLASS.mono}` }, agent.id),
		                h('span', { className: CLASS.cell, style: { flex: 'none' } }, h(StatusPill, { status: 'proposed' })),
		                h('span', { className: CLASS.cell, style: { flex: 'none' } }, `${agent.readPaths.length}`),
		                h('span', { className: CLASS.cell, style: { flex: 'none' } }, `${agent.writeScopes.length}`),
		                h('span', { className: `${CLASS.cell} ${CLASS.muted}` }, agent.task?.subject ?? '—'),
		              ),
		            ),
		      ),
		      h(
		        'p',
		        { className: CLASS.cardMeta },
		        'Read paths are handed to the agent as context; write scopes are what it may modify. A path shown in red is declared but not on disk yet.',
		      ),
		    ),
		
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, `Files claimed by an agent (${providedFiles.length})`),
		      providedFiles.length === 0
		        ? h(Empty, null, 'No file on disk is currently claimed by a declared agent.')
		        : h(
		            'div',
		            { className: CLASS.table },
		            providedFiles.map((file) =>
		              h(
		                'div',
		                { key: file.path, className: CLASS.row },
		                h('span', { className: `${CLASS.cell} ${CLASS.mono}`, style: { flex: 1 } }, file.path),
		                h(
		                  'span',
		                  { className: CLASS.cell, style: { flex: 'none' } },
		                  file.agents.map((id) => h('span', { key: id, className: CLASS.tag, style: { marginLeft: '4px' } }, id)),
		                ),
		                h(
		                  'span',
		                  { className: `${CLASS.cell} ${CLASS.muted}`, style: { flex: 'none' } },
		                  file.components.length === 0 ? '' : `component: ${file.components.join(', ')}`,
		                ),
		              ),
		            ),
		          ),
		    ),
		
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, `Workspace tree (${index.stats.files} files)`),
		      tree.length === 0
		        ? h(Empty, null, 'The workspace scan returned no files.')
		        : h(
		            'div',
		            { className: CLASS.tree },
		            tree.map((node) => h(TreeNode, { key: node.path, node, depth: 0, ownership, expanded: expandedTree, onToggle: onToggleTree })),
		          ),
		      index.unownedFiles.length === 0
		        ? null
		        : h(
		            Collapsible,
		            { summary: `${index.unownedFiles.length} file(s) belong to no declared component or agent` },
		            h(
		              'div',
		              { className: CLASS.table },
		              index.unownedFiles.map((file) => h('div', { key: file, className: `${CLASS.row} ${CLASS.mono} ${CLASS.muted}` }, file)),
		            ),
		          ),
		    ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// Verify
		// ---------------------------------------------------------------------------
		
		/** The verify tab: what is wrong, and how to prove the project still works. */
		function VerifyView({ index }) {
		  const rows = warnings(index, undefined)
		  const manifest = index.manifestPath
		  return h(
		    'div',
		    { className: CLASS.view },
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, `Findings (${rows.length})`),
		      rows.length === 0
		        ? h('div', { className: `${CLASS.ok}` }, 'Nothing is inconsistent: every declared path resolves, no write scopes overlap, and no task is blocked while in progress.')
		        : rows.map((row, index2) =>
		            h(
		              'div',
		              { key: index2, className: CLASS.warnBox, style: { borderColor: row.level === 'err' ? 'var(--pcx-err)' : 'var(--pcx-warn)', marginBottom: '8px' } },
		              row.text,
		            ),
		          ),
		    ),
		
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Commands'),
		      h(
		        'div',
		        { className: CLASS.list },
		        h(
		          'div',
		          { className: CLASS.listItem },
		          h('span', { className: CLASS.muted, style: { minWidth: '90px' } }, 'verify'),
		          h('code', { className: CLASS.mono }, index.project.testCommand === '' ? '(none declared — set project.testCommand)' : index.project.testCommand),
		        ),
		        h(
		          'div',
		          { className: CLASS.listItem },
		          h('span', { className: CLASS.muted, style: { minWidth: '90px' } }, 'run'),
		          h('code', { className: CLASS.mono }, index.project.runCommand === '' ? '(none declared — set project.runCommand)' : index.project.runCommand),
		        ),
		        h(
		          'div',
		          { className: CLASS.listItem },
		          h('span', { className: CLASS.muted, style: { minWidth: '90px' } }, 'manifest'),
		          h('code', { className: CLASS.mono }, manifest),
		        ),
		      ),
		    ),
		
		    h(
		      'section',
		      { className: CLASS.section },
		      h('h2', { className: CLASS.sectionTitle }, 'Coverage'),
		      h(KpiRow, {
		        rows: [
		          { label: 'files on disk', value: `${index.stats.files}` },
		          { label: 'declared paths', value: `${index.stats.declaredPaths}` },
		          { label: 'declared and present', value: `${index.stats.declaredPaths - index.stats.missingPaths}` },
		          { label: 'declared but absent', value: `${index.stats.missingPaths}` },
		          { label: 'unclaimed files', value: `${index.stats.unownedFiles}` },
		        ],
		      }),
		      h('p', { className: CLASS.cardMeta }, 'A declared-but-absent path is work the architecture promises and the tree does not have yet. A high unclaimed count means the manifest has drifted behind the code.'),
		    ),
		
		    index.components.length === 0
		      ? null
		      : h(
		          'section',
		          { className: CLASS.section },
		          h('h2', { className: CLASS.sectionTitle }, 'Per-component resolution'),
		          h(
		            'div',
		            { className: CLASS.table },
		            index.components.map((component) =>
		              h(
		                'div',
		                { key: component.id, className: CLASS.row },
		                h('span', { className: `${CLASS.cell} ${CLASS.mono}`, style: { width: '170px', flex: 'none' } }, component.id),
		                h('span', { className: CLASS.cell, style: { flex: 'none' } }, h(StatusPill, { status: component.status })),
		                h('span', { className: `${CLASS.cell} ${CLASS.present}`, style: { flex: 'none' } }, `${component.presentPaths} present`),
		                h('span', { className: `${CLASS.cell} ${component.missingPaths > 0 ? CLASS.missing : CLASS.muted}`, style: { flex: 'none' } }, `${component.missingPaths} absent`),
		                h('span', { className: `${CLASS.cell} ${CLASS.muted}` }, `${component.fileCount} file(s)`),
		              ),
		            ),
		          ),
		        ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// the panel
		// ---------------------------------------------------------------------------
		
		const TABS = [
		  { id: 'architecture', label: 'Architecture' },
		  { id: 'agents', label: 'Agents' },
		  { id: 'tasks', label: 'Tasks' },
		  { id: 'files', label: 'Files → Agents' },
		  { id: 'verify', label: 'Verify' },
		]
		
		/** The main cockpit panel. */
		function CockpitPanel({ sessions }) {
		  const { index, team, board, boardError, capabilities, loading, error, reload, sessionId, resolvedRoot, rootSource } = useCockpit(sessions)
		  const [tab, setTab] = React.useState('architecture')
		  const [selected, setSelected] = React.useState(undefined)
		  const [expandedAgents, setExpandedAgents] = React.useState(() => new Set())
		  const [expandedTree, setExpandedTree] = React.useState(() => new Set(['docs', 'contracts', 'db', '.cockpit']))
		
		  // The live board is the authority on which tasks already exist. A manifest
		  // task whose subject is already on the board is not offered again, because
		  // creating it twice is how a board fills with duplicates.
		  //
		  // `contract` is the host half's revision. An older host has no POST route at
		  // all, so the panel offers the action only when the host says it exists —
		  // and says which half needs restarting when it does not.
		  const actionsSupported = capabilities !== null && capabilities.contract >= 2
		  const actions = {
		    sessionId,
		    supported: actionsSupported,
		    onDone: reload,
		    /** Hand this agent its task, with the files it is to work from. */
		    sendTask: (agent) =>
		      h(ActionButton, {
		        key: agent.id,
		        label: 'Send task to member',
		        title: 'Message this teammate its task and the files it is handed',
		        disabled: agent.liveStatus === 'not-created' || agent.liveStatus === 'failed',
		        run: async () => {
		          const sections = [`${agent.emoji === '' ? '' : `${agent.emoji} `}${agent.id} — ${agent.role}`]
		          if (agent.purpose !== '') sections.push(agent.purpose)
		          sections.push(agent.task === undefined ? agent.task || 'Your task is not yet declared in the manifest.' : `Task: ${agent.task.subject}`)
		          if (agent.notes !== '') sections.push(agent.notes)
		          if (agent.components.length > 0) sections.push(`Components you own: ${agent.components.map((component) => component.id).join(', ')}`)
		          const read = agent.readPaths.filter((entry) => entry.status !== 'missing')
		          const write = agent.writeScopes.filter((entry) => entry.status !== 'missing')
		          if (read.length > 0) sections.push(['Files you are handed as context:', ...read.map((entry) => `  ${entry.path}`)].join('\n'))
		          if (write.length > 0) sections.push([`Write scopes — yours alone: ${write.map((entry) => entry.path).join(', ')}`].join('\n'))
		          const missing = agent.providedFiles.filter((entry) => entry.status === 'missing')
		          if (missing.length > 0) sections.push(['Declared but not yet on disk:', ...missing.map((entry) => `  ${entry.path}`)].join('\n'))
		          const result = await postAction('send_message', { target: agent.id, message: sections.join('\n\n') }, sessionId)
		          const delivery = result.delivery
		          const state = delivery !== null && typeof delivery === 'object' ? delivery.delivered ?? delivery.status ?? 'sent' : 'sent'
		          return `Message ${state}.`
		        },
		        onDone: reload,
		      }),
		  }
		
		  const toggleAgent = React.useCallback((id) => {
		    setExpandedAgents((previous) => {
		      const next = new Set(previous)
		      if (next.has(id)) next.delete(id)
		      else next.add(id)
		      return next
		    })
		  }, [])
		  const toggleTree = React.useCallback((path) => {
		    setExpandedTree((previous) => {
		      const next = new Set(previous)
		      if (next.has(path)) next.delete(path)
		      else next.add(path)
		      return next
		    })
		  }, [])
		
		  if (error !== null && index === null) {
		    return h(
		      'div',
		      { className: CLASS.root },
		      h('div', { className: CLASS.header }, h('h1', { className: CLASS.title }, 'Project Cockpit')),
		      h(
		        'div',
		        { className: CLASS.body },
		        h('div', { className: CLASS.warnBox, style: { borderColor: 'var(--pcx-err)' } }, h('strong', null, 'The cockpit could not read the project. '), error),
		        h('p', { className: CLASS.cardMeta }, 'The host half serves this panel at /api/project-cockpit. If it was disabled in the profile, the panel has nothing to read.'),
		        h('button', { type: 'button', className: `${CLASS.button} ${CLASS.buttonPrimary}`, onClick: reload }, 'Retry'),
		      ),
		    )
		  }
		
		  if (index === null) {
		    return h(
		      'div',
		      { className: CLASS.root },
		      h('div', { className: CLASS.header }, h('h1', { className: CLASS.title }, 'Project Cockpit')),
		      h('div', { className: CLASS.body }, h(Empty, null, loading ? 'Reading the project…' : 'No data.')),
		    )
		  }
		
		  const counts = {
		    architecture: index.components.length,
		    agents: index.agents.length,
		    tasks: index.tasks.length,
		    files: index.stats.files,
		    verify: warnings(index, team).length,
		  }
		
		  return h(
		    'div',
		    { className: CLASS.root },
		    h(
		      'div',
		      { className: CLASS.header },
		      h(
		        'h1',
		        { className: CLASS.title },
		        index.project.name === '' ? 'Untitled project' : index.project.name,
		        h(StatusPill, { status: index.project.stage === 'shipped' ? 'done' : index.project.stage === 'design' ? 'proposed' : 'in-progress', label: index.project.stage }),
		      ),
		      index.project.summary === '' ? null : h('p', { className: CLASS.subtitle }, index.project.summary),
		      h(
		        'div',
		        { className: CLASS.chipRow },
		        h('span', { className: CLASS.chip }, h('span', { className: `${CLASS.chipDot}`, style: { background: 'var(--pcx-brand)' } }), `${index.stats.components} components`),
		        h('span', { className: CLASS.chip }, h('span', { className: `${CLASS.chipDot}`, style: { background: 'var(--pcx-ok)' } }), `${index.agents.length} agents planned`),
		        h(
		          'span',
		          { className: CLASS.chip },
		          h('span', { className: `${CLASS.chipDot}`, style: { background: team === undefined ? 'var(--pcx-idle)' : 'var(--pcx-ok)' } }),
		          team === undefined ? 'no live team in this session' : `${(team.members ?? []).length - 1} teammate(s) live`,
		        ),
		        h('span', { className: CLASS.chip }, `${index.stats.files} files`),
		        index.stats.missingPaths > 0
		          ? h('span', { className: CLASS.chip, style: { borderColor: 'var(--pcx-warn)' } }, h('span', { className: `${CLASS.chipDot}`, style: { background: 'var(--pcx-warn)' } }), `${index.stats.missingPaths} declared path(s) absent`)
		          : null,
		        index.collisions.length > 0
		          ? h('span', { className: CLASS.chip, style: { borderColor: 'var(--pcx-err)' } }, h('span', { className: `${CLASS.chipDot}`, style: { background: 'var(--pcx-err)' } }), `${index.collisions.length} write-scope overlap(s)`)
		          : null,
		      ),
		      h(
		        'div',
		        { className: CLASS.actions },
		        h('button', { type: 'button', className: `${CLASS.button} ${CLASS.buttonPrimary}`, onClick: reload, disabled: loading }, loading ? 'Refreshing…' : 'Refresh'),
		        h('span', { className: `${CLASS.muted} ${CLASS.mono}` }, `${index.root}${sessionId === undefined ? '' : ` · session ${sessionId.slice(0, 8)}`}`),
		      ),
		      h(
		        'div',
		        { className: CLASS.tabs, role: 'tablist' },
		        TABS.map((entry) =>
		          h(
		            'button',
		            {
		              key: entry.id,
		              type: 'button',
		              role: 'tab',
		              'aria-selected': tab === entry.id,
		              className: tab === entry.id ? `${CLASS.tab} ${CLASS.tabActive}` : CLASS.tab,
		              onClick: () => setTab(entry.id),
		            },
		            entry.label,
		            h('span', { className: CLASS.tabCount }, `${counts[entry.id] ?? 0}`),
		          ),
		        ),
		      ),
		    ),
		    h(
		      'div',
		      { className: CLASS.body },
		      tab === 'architecture' ? h(ArchitectureView, { index, selected, onSelect: setSelected }) : null,
		      tab === 'agents' ? h(AgentsView, { index, team, expanded: expandedAgents, onToggle: toggleAgent, actions }) : null,
		      tab === 'tasks' ? h(TasksView, { index, team, board, boardError, actions }) : null,
		      tab === 'files' ? h(FilesView, { index, expandedTree, onToggleTree: toggleTree }) : null,
		      tab === 'verify' ? h(VerifyView, { index }) : null,
		    ),
		    h(
		      'div',
		      { className: CLASS.footer },
		      // Which project this is, and why. The cockpit reads any project, so the
		      // directory it resolved is part of the answer, not a detail.
		      h('span', { className: CLASS.mono, title: rootSource === null ? undefined : `chosen by: ${rootSource}` }, resolvedRoot ?? index.root),
		      rootSource === null ? null : h('span', { className: CLASS.muted }, rootSource),
		      h('span', { className: CLASS.mono }, index.manifestPath),
		      h('span', null, `read ${new Date(index.generatedAt).toLocaleTimeString()}`),
		      index.truncated ? h('span', { className: CLASS.warn }, 'scan truncated') : null,
		      h('span', { className: CLASS.muted }, 'read-only'),
		    ),
		  )
		}
		
		// ---------------------------------------------------------------------------
		// registration
		// ---------------------------------------------------------------------------
		
		/**
		 * Client plugin entry.
		 * @param ctx client context carrying `slots` and `sessions`.
		 */
		function apply(ctx) {
		  installStyles()
		  const sessions = ctx.sessions
		
		  // The toolbar glyph. Its own button chrome, label and accessibility belong to
		  // the sidebar; a panellist entry supplies the icon and nothing else.
		  ctx.slots.inject('sidebar.panellist', () =>
		    ctx.slots.register(
		      {
		        name: 'sidebar.panellist',
		        id: PANEL_ID,
		        order: 40,
		        label: 'Project Cockpit',
		      },
		      (ownerProps) => h(CockpitGlyph, { size: ownerProps?.size ?? 16, active: ownerProps?.active === true }),
		    ),
		  )
		
		  // The page itself, keyed by the same id the sidebar button selects.
		  ctx.slots.inject('main', () =>
		    ctx.slots.register(
		      {
		        name: 'main',
		        key: PANEL_ID,
		        inject: () => ({ sessions }),
		      },
		      () => h(CockpitPanel, { sessions }),
		    ),
		  )
		}

		exports.apply = apply;
		exports.inject = inject;
		exports.name = name;
		return module.exports;
	}
});
