package main

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/pem"
	"fmt"
	"math/big"
	"net"
	"os"
	"path/filepath"
	"time"
)

// The development PKI. It is generated fresh on every run and written under a gitignored directory;
// nothing here is ever committed. The CA signs the device leaves control-api issues, so the edge
// (client CA) and ingest-api (trust bundle) share exactly the authority that issued them.

const (
	fileCACert    = "dev-ca.crt"
	fileCAKey     = "dev-ca.key"
	fileEdgeCert  = "edge-server.crt"
	fileEdgeKey   = "edge-server.key"
	fileTokenKey  = "token.key"
	fileTokenPub  = "token.pub.pem"
	fileMarkerTXT = "README.txt"
)

func generatePKI(dir string) error {
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return fmt.Errorf("create pki dir: %w", err)
	}

	caCert, caKey, err := newCA()
	if err != nil {
		return err
	}
	if err := writePEM(filepath.Join(dir, fileCACert), "CERTIFICATE", caCert.Raw, 0o644); err != nil {
		return err
	}
	if err := writeKeyPEM(filepath.Join(dir, fileCAKey), caKey); err != nil {
		return err
	}

	edgeCert, edgeKey, err := newServerLeaf(caCert, caKey)
	if err != nil {
		return err
	}
	if err := writePEM(filepath.Join(dir, fileEdgeCert), "CERTIFICATE", edgeCert.Raw, 0o644); err != nil {
		return err
	}
	if err := writeKeyPEM(filepath.Join(dir, fileEdgeKey), edgeKey); err != nil {
		return err
	}

	tokenKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return fmt.Errorf("generate token key: %w", err)
	}
	if err := writeKeyPEM(filepath.Join(dir, fileTokenKey), tokenKey); err != nil {
		return err
	}
	pubDER, err := x509.MarshalPKIXPublicKey(&tokenKey.PublicKey)
	if err != nil {
		return fmt.Errorf("marshal token public key: %w", err)
	}
	if err := writePEM(filepath.Join(dir, fileTokenPub), "PUBLIC KEY", pubDER, 0o644); err != nil {
		return err
	}

	note := "Generated by `authlab pki`. LAB-ONLY: these keys are development material, they are\n" +
		"regenerated on every run, and they must never be used outside localdev. The directory is\n" +
		"gitignored (localdev/.gitignore).\n"
	if err := os.WriteFile(filepath.Join(dir, fileMarkerTXT), []byte(note), 0o644); err != nil {
		return err
	}

	fmt.Printf("pki: wrote %s (CA), %s (edge server), %s/%s (access-token key) in %s\n",
		fileCACert, fileEdgeCert, fileTokenKey, fileTokenPub, dir)
	return nil
}

func newCA() (*x509.Certificate, *ecdsa.PrivateKey, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate CA key: %w", err)
	}
	serial, err := randomSerial()
	if err != nil {
		return nil, nil, err
	}
	now := time.Now().UTC()
	tmpl := &x509.Certificate{
		SerialNumber:          serial,
		Subject:               pkix.Name{CommonName: "Shadow AI Capture Auth Lab CA", Organization: []string{"Shadow AI Capture Auth Lab"}},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(365 * 24 * time.Hour),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLen:            1,
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, tmpl, &key.PublicKey, key)
	if err != nil {
		return nil, nil, fmt.Errorf("create CA certificate: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, fmt.Errorf("parse CA certificate: %w", err)
	}
	return cert, key, nil
}

func newServerLeaf(ca *x509.Certificate, caKey *ecdsa.PrivateKey) (*x509.Certificate, *ecdsa.PrivateKey, error) {
	key, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return nil, nil, fmt.Errorf("generate edge key: %w", err)
	}
	serial, err := randomSerial()
	if err != nil {
		return nil, nil, err
	}
	now := time.Now().UTC()
	tmpl := &x509.Certificate{
		SerialNumber: serial,
		Subject:      pkix.Name{CommonName: "edge", Organization: []string{"Shadow AI Capture Auth Lab"}},
		// The host reaches the edge at 127.0.0.1:LAB_EDGE_PORT; the container reaches itself at edge.
		DNSNames:    []string{"edge", "localhost"},
		IPAddresses: []net.IP{net.ParseIP("127.0.0.1"), net.ParseIP("::1")},
		NotBefore:   now.Add(-time.Hour),
		NotAfter:    now.Add(365 * 24 * time.Hour),
		KeyUsage:    x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}
	der, err := x509.CreateCertificate(rand.Reader, tmpl, ca, &key.PublicKey, caKey)
	if err != nil {
		return nil, nil, fmt.Errorf("create edge certificate: %w", err)
	}
	cert, err := x509.ParseCertificate(der)
	if err != nil {
		return nil, nil, fmt.Errorf("parse edge certificate: %w", err)
	}
	return cert, key, nil
}

func writePEM(path, blockType string, der []byte, mode os.FileMode) error {
	return os.WriteFile(path, pem.EncodeToMemory(&pem.Block{Type: blockType, Bytes: der}), mode)
}

func writeKeyPEM(path string, key *ecdsa.PrivateKey) error {
	der, err := x509.MarshalECPrivateKey(key)
	if err != nil {
		return fmt.Errorf("marshal EC private key: %w", err)
	}
	return writePEM(path, "EC PRIVATE KEY", der, 0o600)
}

func randomSerial() (*big.Int, error) {
	limit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, limit)
	if err != nil {
		return nil, fmt.Errorf("generate serial: %w", err)
	}
	return serial, nil
}
