package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgconn"
)

// The statements. Every one is tenant-scoped by an explicit tenant_id = $1 as well as by row-level
// security, and every value is a bound parameter.
const (
	// set_config's third argument makes the setting transaction-local, so a pooled connection
	// never carries one request's tenant into the next.
	sqlSetTenant = `SELECT set_config('app.tenant_id', $1::text, true)`

	sqlTenant = `
SELECT tenant_id::text, status, content_search, ingest_enabled, read_enabled
  FROM ops.tenant
 WHERE tenant_id = $1::uuid`

	// The claim is the single-use mechanism for upload grants: two concurrent uploads under one
	// grant cannot both match `used_at IS NULL`.
	sqlClaimGrant = `
UPDATE ops.grant
   SET used_at = $4::timestamptz
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid AND event_id = $3::uuid
   AND decision = 'granted' AND used_at IS NULL AND expires_at > $4::timestamptz
RETURNING grant_id::text, event_id::text, device_id::text, coalesce(submission_id::text, ''),
          decision, expires_at, used_at`

	sqlGrant = `
SELECT grant_id::text, event_id::text, device_id::text, coalesce(submission_id::text, ''),
       decision, expires_at, used_at
  FROM ops.grant
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid`

	// The submission's prompt kind, and the tenant's content retention: the policy for the
	// highest-severity class in the submission's labels at M3, else the longest content policy at
	// M3, else the 'content' retention class default. This mirrors ops.event_ttl_days for events.
	sqlUploadContext = `
WITH sub AS (
  SELECT prompt_kind, labels
    FROM ingest.submission
   WHERE tenant_id = $1::uuid AND submission_id = nullif($2::text, '')::uuid
), top_class AS (
  SELECT l.value->>'class' AS class_code
    FROM sub
   CROSS JOIN LATERAL jsonb_array_elements(
           CASE WHEN jsonb_typeof(sub.labels) = 'array' THEN sub.labels ELSE '[]'::jsonb END) AS l(value)
    JOIN ref.data_class d ON d.class_code = l.value->>'class'
   ORDER BY CASE d.default_severity WHEN 'critical' THEN 0 WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END,
            coalesce((l.value->>'score')::numeric, 0) DESC
   LIMIT 1
)
SELECT coalesce((SELECT prompt_kind FROM sub), ''),
       coalesce(
         (SELECT rp.ttl_days
            FROM ops.retention_policy rp
            JOIN top_class c ON c.class_code = rp.data_class
           WHERE rp.tenant_id = $1::uuid AND rp.applies_to = 'content' AND rp.collection_mode = 'm3'),
         (SELECT max(rp.ttl_days)
            FROM ops.retention_policy rp
           WHERE rp.tenant_id = $1::uuid AND rp.applies_to = 'content' AND rp.collection_mode = 'm3'),
         (SELECT rc.default_ttl_days FROM ref.retention_class rc WHERE rc.retention_class = 'content'))`

	sqlInsertContent = `
INSERT INTO ops.content (tenant_id, object_id, event_id, submission_id, grant_id, key_version, ciphertext,
                         plaintext_size_bytes, raw_digest, retention_class, prompt_kind, created_at, expires_at)
VALUES ($1::uuid, $2::uuid, $3::uuid, nullif($4::text, '')::uuid, $5::uuid, $6::text, $7::bytea,
        $8::int, $9::text, $10::text, nullif($11::text, ''), $12::timestamptz, $13::timestamptz)`

	sqlMarkUploaded = `
UPDATE ingest.submission
   SET content_state = 'uploaded'
 WHERE tenant_id = $1::uuid AND submission_id = $2::uuid AND content_state IN ('not_captured', 'local_only')`

	// The tsv column is generated by the database from body.
	sqlPutSearchText = `
INSERT INTO ingest.search_text (tenant_id, submission_id, unit_kind, unit_index, body, expires_at)
VALUES ($1::uuid, $2::uuid, $3::text, $4::int, $5::text, $6::timestamptz)
ON CONFLICT (tenant_id, submission_id, unit_kind, unit_index) DO UPDATE
   SET body = EXCLUDED.body,
       expires_at = EXCLUDED.expires_at`

	sqlContentColumns = `object_id::text, event_id::text, coalesce(submission_id::text, ''), grant_id::text,
       key_version, plaintext_size_bytes, raw_digest, retention_class, coalesce(prompt_kind, ''),
       created_at, expires_at`

	sqlContentForEvent = `
SELECT ` + sqlContentColumns + `
  FROM ops.content
 WHERE tenant_id = $1::uuid AND event_id = $2::uuid`

	sqlContentForObject = `
SELECT ` + sqlContentColumns + `, ciphertext
  FROM ops.content
 WHERE tenant_id = $1::uuid AND object_id = $2::uuid`

	sqlInsertRetrievalGrant = `
INSERT INTO ops.retrieval_grant (tenant_id, grant_id, event_id, object_id, submission_id, principal,
                                 case_reference, second_approver, issued_at, expires_at, raw_digest)
VALUES ($1::uuid, $2::uuid, $3::uuid, $4::uuid, nullif($5::text, '')::uuid, $6::text,
        $7::text, $8::text, $9::timestamptz, $10::timestamptz, $11::text)`

	sqlRetrievalGrantColumns = `grant_id::text, event_id::text, object_id::text, coalesce(submission_id::text, ''),
       principal, case_reference, second_approver, issued_at, expires_at, used_at,
       coalesce(used_by, ''), raw_digest`

	sqlRetrievalGrant = `
SELECT ` + sqlRetrievalGrantColumns + `
  FROM ops.retrieval_grant
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid`

	// The claim is the single-use mechanism for retrieval grants.
	sqlClaimRetrievalGrant = `
UPDATE ops.retrieval_grant
   SET used_at = $3::timestamptz, used_by = $4::text
 WHERE tenant_id = $1::uuid AND grant_id = $2::uuid AND used_at IS NULL
RETURNING ` + sqlRetrievalGrantColumns

	sqlLatestReceipt = `
SELECT receipt_id::text
  FROM ops.erasure_receipt
 WHERE tenant_id = $1::uuid
 ORDER BY completed_at DESC NULLS LAST, requested_at DESC
 LIMIT 1`

	// The chain hashes are computed by the ops.audit_chain() trigger.
	sqlAppendAudit = `
INSERT INTO ops.audit (tenant_id, actor_type, actor_id, action, object_type, object_id,
                       case_reference, detail, occurred_at)
VALUES ($1::uuid, $2::text, $3::text, $4::text, $5::text, nullif($6::text, ''),
        nullif($7::text, ''), $8::jsonb, $9::timestamptz)`
)

// The three search statements share one shape: they join the index to the submission so a search
// can be narrowed by person, tool, device, mode and receive time, they skip expired index rows, and
// they page newest first on a total order so a keyset cursor resumes exactly. Parameters: $1
// tenant, $2 search text, $3 unit kind (empty for both), $4 limit, $5 now, $6-$11 filters (an empty
// text or a NULL instant adds no predicate), $12-$15 the cursor (all NULL on the first page), and
// for the fuzzy form $16 the minimum similarity.
const searchTemplate = `
SELECT st.submission_id::text, st.unit_kind, st.unit_index, %s, s.received_at
  FROM ingest.search_text st
  JOIN ingest.submission s
    ON s.tenant_id = st.tenant_id AND s.submission_id = st.submission_id
 WHERE st.tenant_id = $1::uuid
   AND %s
   AND ($3::text = '' OR st.unit_kind = $3::text)
   AND st.expires_at > $5::timestamptz
   AND ($6::text = '' OR s.user_ref = $6::text)
   AND ($7::text = '' OR s.tool_fingerprint = $7::text)
   AND ($8::text = '' OR s.device_id::text = $8::text)
   AND ($9::text = '' OR s.collection_mode = $9::text)
   AND ($10::timestamptz IS NULL OR s.received_at >= $10::timestamptz)
   AND ($11::timestamptz IS NULL OR s.received_at < $11::timestamptz)
   AND ($12::timestamptz IS NULL OR
        (s.received_at, st.submission_id, st.unit_kind, st.unit_index)
          < ($12::timestamptz, $13::uuid, $14::text, $15::int))
 ORDER BY s.received_at DESC, st.submission_id DESC, st.unit_kind DESC, st.unit_index DESC
 LIMIT $4::int`

var (
	// Terms: the vault builds $2 as tsquery text from sanitised terms, so to_tsquery cannot fail.
	sqlSearchTerms = fmt.Sprintf(searchTemplate,
		`ts_headline('simple', st.body, to_tsquery('simple', $2::text),
                   'StartSel=<em>, StopSel=</em>, MaxFragments=1, MaxWords=24, MinWords=6, FragmentDelimiter= … '),
       ts_rank(st.tsv, to_tsquery('simple', $2::text))`,
		`st.tsv @@ to_tsquery('simple', $2::text)`)
	// Substring and fuzzy match attachment names only, through the partial trigram index; the
	// literal unit_kind predicate is what lets the planner use it. $2 is an escaped LIKE pattern.
	sqlSearchSubstring = fmt.Sprintf(searchTemplate,
		`st.body, similarity(st.body, $2::text)`,
		`st.unit_kind = 'attachment_name' AND st.body ILIKE '%' || $2::text || '%'`)
	sqlSearchFuzzy = fmt.Sprintf(searchTemplate,
		`st.body, similarity(st.body, $2::text)`,
		`st.unit_kind = 'attachment_name' AND st.body % $2::text AND similarity(st.body, $2::text) >= $16::float8`)
)

// DB is the PostgreSQL store.
type DB struct {
	db *sql.DB
}

// New wraps an open pool.
func New(db *sql.DB) *DB { return &DB{db: db} }

// Ping makes one round trip to the database.
func (d *DB) Ping(ctx context.Context) error {
	var one int
	return d.db.QueryRowContext(ctx, `SELECT 1`).Scan(&one)
}

// InTenant implements Store.
func (d *DB) InTenant(ctx context.Context, tenantID string, fn func(Tx) error) error {
	tx, err := d.db.BeginTx(ctx, nil)
	if err != nil {
		return fmt.Errorf("store: begin: %w", err)
	}
	defer func() { _ = tx.Rollback() }()
	if _, err := tx.ExecContext(ctx, sqlSetTenant, tenantID); err != nil {
		return fmt.Errorf("store: set tenant: %w", err)
	}
	if err := fn(&sqlTx{tx: tx, tenant: tenantID}); err != nil {
		return err
	}
	if err := tx.Commit(); err != nil {
		return fmt.Errorf("store: commit: %w", err)
	}
	return nil
}

type sqlTx struct {
	tx     *sql.Tx
	tenant string
}

func (t *sqlTx) Tenant(ctx context.Context) (Tenant, error) {
	var out Tenant
	var tier string
	err := t.tx.QueryRowContext(ctx, sqlTenant, t.tenant).Scan(&out.TenantID, &out.Status, &tier, &out.IngestEnabled, &out.ReadEnabled)
	if err != nil {
		return Tenant{}, notFound("tenant", err)
	}
	out.ContentSearch = SearchTier(tier)
	return out, nil
}

func (t *sqlTx) ClaimGrant(ctx context.Context, grantID, eventID string, now time.Time) (Grant, error) {
	g, err := scanGrant(t.tx.QueryRowContext(ctx, sqlClaimGrant, t.tenant, grantID, eventID, now))
	return g, notFound("claim grant", err)
}

func (t *sqlTx) Grant(ctx context.Context, grantID string) (Grant, error) {
	g, err := scanGrant(t.tx.QueryRowContext(ctx, sqlGrant, t.tenant, grantID))
	return g, notFound("grant", err)
}

func (t *sqlTx) UploadContext(ctx context.Context, submissionID string) (UploadContext, error) {
	var out UploadContext
	var days sql.NullInt64
	if err := t.tx.QueryRowContext(ctx, sqlUploadContext, t.tenant, submissionID).Scan(&out.PromptKind, &days); err != nil {
		return UploadContext{}, fmt.Errorf("store: upload context: %w", err)
	}
	if !days.Valid || days.Int64 <= 0 {
		return UploadContext{}, errors.New("store: no content retention is configured (ref.retention_class 'content')")
	}
	out.RetentionDays = int(days.Int64)
	return out, nil
}

func (t *sqlTx) InsertContent(ctx context.Context, c Content) error {
	_, err := t.tx.ExecContext(ctx, sqlInsertContent, t.tenant, c.ObjectID, c.EventID, c.SubmissionID, c.GrantID,
		c.KeyVersion, c.Ciphertext, c.PlaintextSizeBytes, c.RawDigest, c.RetentionClass, c.PromptKind,
		c.CreatedAt, c.ExpiresAt)
	var pgErr *pgconn.PgError
	if errors.As(err, &pgErr) && pgErr.Code == "23505" {
		return ErrContentExists
	}
	if err != nil {
		return fmt.Errorf("store: insert content: %w", err)
	}
	return nil
}

func (t *sqlTx) MarkUploaded(ctx context.Context, submissionID string) error {
	if _, err := t.tx.ExecContext(ctx, sqlMarkUploaded, t.tenant, submissionID); err != nil {
		return fmt.Errorf("store: mark uploaded: %w", err)
	}
	return nil
}

func (t *sqlTx) PutSearchText(ctx context.Context, u SearchUnit) error {
	if _, err := t.tx.ExecContext(ctx, sqlPutSearchText, t.tenant, u.SubmissionID, u.UnitKind, u.UnitIndex, u.Body, u.ExpiresAt); err != nil {
		return fmt.Errorf("store: search text: %w", err)
	}
	return nil
}

func (t *sqlTx) ContentForEvent(ctx context.Context, eventID string) (Content, error) {
	var c Content
	err := t.tx.QueryRowContext(ctx, sqlContentForEvent, t.tenant, eventID).Scan(contentFields(&c)...)
	c.TenantID = t.tenant
	return c, notFound("content", err)
}

func (t *sqlTx) ContentForObject(ctx context.Context, objectID string) (Content, error) {
	var c Content
	err := t.tx.QueryRowContext(ctx, sqlContentForObject, t.tenant, objectID).Scan(append(contentFields(&c), &c.Ciphertext)...)
	c.TenantID = t.tenant
	return c, notFound("content", err)
}

func (t *sqlTx) InsertRetrievalGrant(ctx context.Context, g RetrievalGrant) error {
	if _, err := t.tx.ExecContext(ctx, sqlInsertRetrievalGrant, t.tenant, g.GrantID, g.EventID, g.ObjectID, g.SubmissionID,
		g.Principal, g.CaseReference, g.SecondApprover, g.IssuedAt, g.ExpiresAt, g.RawDigest); err != nil {
		return fmt.Errorf("store: insert retrieval grant: %w", err)
	}
	return nil
}

func (t *sqlTx) RetrievalGrant(ctx context.Context, grantID string) (RetrievalGrant, error) {
	g, err := scanRetrievalGrant(t.tx.QueryRowContext(ctx, sqlRetrievalGrant, t.tenant, grantID))
	return g, notFound("retrieval grant", err)
}

func (t *sqlTx) ClaimRetrievalGrant(ctx context.Context, grantID, usedBy string, now time.Time) (RetrievalGrant, error) {
	g, err := scanRetrievalGrant(t.tx.QueryRowContext(ctx, sqlClaimRetrievalGrant, t.tenant, grantID, now, usedBy))
	return g, notFound("claim retrieval grant", err)
}

func (t *sqlTx) Search(ctx context.Context, q SearchQuery) ([]SearchHit, error) {
	args := []any{t.tenant, q.Text, q.UnitKind, q.Limit, q.Now,
		q.Filters.Subject, q.Filters.Tool, q.Filters.Device, q.Filters.Mode,
		nullTime(q.Filters.ReceivedFrom), nullTime(q.Filters.ReceivedTo)}
	if c := q.Cursor; c != nil {
		args = append(args, c.ReceivedAt, c.SubmissionID, c.UnitKind, c.UnitIndex)
	} else {
		args = append(args, nil, nil, nil, nil)
	}
	var stmt string
	switch q.Form {
	case FormTerms:
		stmt = sqlSearchTerms
	case FormSubstring:
		stmt = sqlSearchSubstring
	case FormFuzzy:
		stmt = sqlSearchFuzzy
		args = append(args, q.MinSimilar)
	default:
		return nil, fmt.Errorf("store: unknown search form %q", q.Form)
	}
	rows, err := t.tx.QueryContext(ctx, stmt, args...)
	if err != nil {
		return nil, fmt.Errorf("store: search: %w", err)
	}
	defer rows.Close()
	var hits []SearchHit
	for rows.Next() {
		var h SearchHit
		var rank sql.NullFloat64
		if err := rows.Scan(&h.SubmissionID, &h.UnitKind, &h.UnitIndex, &h.Snippet, &rank, &h.ReceivedAt); err != nil {
			return nil, fmt.Errorf("store: search row: %w", err)
		}
		h.Rank = rank.Float64
		hits = append(hits, h)
	}
	return hits, rows.Err()
}

func (t *sqlTx) LatestReceiptID(ctx context.Context) (string, error) {
	var id string
	err := t.tx.QueryRowContext(ctx, sqlLatestReceipt, t.tenant).Scan(&id)
	if errors.Is(err, sql.ErrNoRows) {
		return "", nil
	}
	if err != nil {
		return "", fmt.Errorf("store: latest receipt: %w", err)
	}
	return id, nil
}

func (t *sqlTx) AppendAudit(ctx context.Context, e AuditEntry) error {
	detail := e.Detail
	if detail == nil {
		detail = map[string]any{}
	}
	raw, err := json.Marshal(detail)
	if err != nil {
		return fmt.Errorf("store: audit detail: %w", err)
	}
	if _, err := t.tx.ExecContext(ctx, sqlAppendAudit, t.tenant, e.ActorType, e.ActorID, e.Action, e.ObjectType,
		e.ObjectID, e.CaseReference, raw, e.OccurredAt); err != nil {
		return fmt.Errorf("store: audit: %w", err)
	}
	return nil
}

type rowScanner interface{ Scan(dest ...any) error }

func scanGrant(row rowScanner) (Grant, error) {
	var g Grant
	var expires, used sql.NullTime
	if err := row.Scan(&g.GrantID, &g.EventID, &g.DeviceID, &g.SubmissionID, &g.Decision, &expires, &used); err != nil {
		return Grant{}, err
	}
	g.ExpiresAt, g.UsedAt = expires.Time, used.Time
	return g, nil
}

func scanRetrievalGrant(row rowScanner) (RetrievalGrant, error) {
	var g RetrievalGrant
	var used sql.NullTime
	if err := row.Scan(&g.GrantID, &g.EventID, &g.ObjectID, &g.SubmissionID, &g.Principal, &g.CaseReference,
		&g.SecondApprover, &g.IssuedAt, &g.ExpiresAt, &used, &g.UsedBy, &g.RawDigest); err != nil {
		return RetrievalGrant{}, err
	}
	g.UsedAt = used.Time
	return g, nil
}

func contentFields(c *Content) []any {
	return []any{&c.ObjectID, &c.EventID, &c.SubmissionID, &c.GrantID, &c.KeyVersion, &c.PlaintextSizeBytes,
		&c.RawDigest, &c.RetentionClass, &c.PromptKind, &c.CreatedAt, &c.ExpiresAt}
}

// notFound turns sql.ErrNoRows into ErrNotFound and labels any other error.
func notFound(what string, err error) error {
	switch {
	case err == nil:
		return nil
	case errors.Is(err, sql.ErrNoRows):
		return ErrNotFound
	default:
		return fmt.Errorf("store: %s: %w", what, err)
	}
}

func nullTime(t time.Time) any {
	if t.IsZero() {
		return nil
	}
	return t
}
