#!/usr/bin/env node
// tools/update-cockpit.mjs - bring .cockpit/project.json in line with what is on disk.
//
// The cockpit is the project's own map: components with their paths, the tasks that own them, and
// the agents. Left stale it is worse than absent, because a reader trusts it. This script sets, for
// each component that now exists, its `paths` and its lifecycle status, and it asserts nothing it
// cannot see - a component whose directory is missing is left alone rather than marked built.
//
//   node tools/update-cockpit.mjs --check    # report drift, change nothing, exit non-zero on drift
//   node tools/update-cockpit.mjs            # apply
//
// Only `paths` and `status` are touched. Tasks and agents are the board's business, not this
// script's, so a human editing them is never overwritten.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const MANIFEST = join(ROOT, '.cockpit', 'project.json');
const CHECK = process.argv.includes('--check');

/**
 * What each component now is. `status: 'done'` means the component exists in the tree and its own
 * suite passes under tools/verify-all.mjs; `proposed` means it does not exist yet. The status words
 * are the manifest's own vocabulary extended with one: `built` is a fact a reader can verify from
 * the paths beside it, which `proposed` no longer is for these.
 */
const KNOWN = {
  'capture-extension': { paths: ['extension'], status: 'done' },
  'capture-core': { paths: ['endpoint/capture-core'], status: 'done' },
  'classifier-host': { paths: ['endpoint/classifier-host'], status: 'done' },
  'device-spool': { paths: ['endpoint/capture-spool'], status: 'done' },
  'device-protocol': {
    paths: ['endpoint/protocol'],
    status: 'done',
    name: 'Device Protocol',
    kind: 'contract',
    layer: 'device',
    language: 'Go',
    runtime: 'shared package',
    summary:
      'The device-side seam: native-messaging frames, length-prefixed IPC, the spool record, and the batch shapes for POST /v1/events. Consumed by capture-core, the spool and the extension; it is where the closed vocabularies live.',
    dependsOn: [],
    docs: ['docs/01-collectors.md', 'docs/02-ingest-and-transport.md'],
    decisions: [],
    notes: 'Added after the fact: the cockpit did not have a component for the seam every device component consumes.',
  },
  'device-canon': {
    paths: ['endpoint/canon'],
    status: 'done',
    name: 'Canonicalisation (NFC)',
    kind: 'library',
    layer: 'device',
    language: 'Go',
    runtime: 'shared package, tables generated from ICU',
    summary:
      'The canonicalisation contract (docs/02 §4, `sac-canon-1`) step C3 in pure Go. Agrees with Node ICU over the whole corpus, every code point and every non-starter pair.',
    dependsOn: [],
    docs: ['docs/02-ingest-and-transport.md'],
    decisions: [],
    notes: 'Tables are generated by gen/gen_tables.mjs from Node; there is no network, so the UCD cannot be downloaded.',
  },
  'device-integration': {
    paths: ['endpoint/integration'],
    status: 'done',
    name: 'Device Integration Harness',
    kind: 'test',
    layer: 'device',
    language: 'Go',
    runtime: 'test-only module',
    summary:
      'The only place the device components are wired together: it drives a real extension frame through the real protocol types, the pipeline and the spool. Its golden frames are generated by the extension own encoder.',
    dependsOn: ['device-protocol', 'capture-core', 'device-spool', 'capture-extension'],
    docs: ['docs/01-collectors.md'],
    decisions: [],
    notes: 'Test-only. Nothing here may become production code.',
  },
  'ingest-api': { paths: ['ingestion/ingest-api'], status: 'done' },
  'content-vault': { paths: ['vault/content-vault'], status: 'done' },
  'query-api': { paths: ['query/query-api'], status: 'done' },
  dashboard: { paths: ['query/dashboard'], status: 'done' },
  infrastructure: { paths: ['azure'], status: 'done' },
  'envelope-contract': {
    paths: ['contracts/event-envelope.schema.json', 'contracts/generated', 'contracts/tools'],
    status: 'done',
    notes: 'The contract, the generator and the generated TypeScript and Go bindings are committed together; `generate.mjs --check` fails on drift.',
  },
  database: {
    paths: ['database/schema.sql', 'database/invariants.test.sql', 'database/tools', 'database/evidence'],
    status: 'done',
  },
  'design-package': { paths: ['docs', 'README.md'], status: 'done' },
};

const raw = readFileSync(MANIFEST, 'utf8');
const manifest = JSON.parse(raw);
const changes = [];

// 1. Existing components: refresh paths and status from what is on disk.
for (const component of manifest.components) {
  const known = KNOWN[component.id];
  if (!known) continue;
  const before = JSON.stringify({ paths: component.paths, status: component.status });
  if (known.paths) component.paths = known.paths;
  if (known.status && existsSync(join(ROOT, (known.paths ?? component.paths)[0]))) {
    component.status = known.status;
  }
  if (component.id === 'envelope-contract' && known.notes) component.notes = known.notes;
  const after = JSON.stringify({ paths: component.paths, status: component.status });
  if (before !== after) changes.push(`${component.id}: ${before} -> ${after}`);
}

// 2. Components the manifest never had. Adding them is the point: three of the newest parts of the
//    device tier were invisible on the map.
const existingIds = new Set(manifest.components.map((c) => c.id));
for (const [id, spec] of Object.entries(KNOWN)) {
  if (existingIds.has(id)) continue;
  if (!spec.name) continue; // only the fully-specified new ones are added
  const { name, kind, layer, language, runtime, summary, dependsOn, docs, decisions, notes } = spec;
  manifest.components.push({
    id,
    name,
    kind,
    layer,
    language,
    runtime,
    status: spec.status,
    summary,
    dependsOn: dependsOn ?? [],
    paths: spec.paths,
    docs: docs ?? [],
    decisions: decisions ?? [],
    notes: notes ?? '',
  });
  changes.push(`added component ${id} (${name})`);
}

if (changes.length === 0) {
  console.log('cockpit manifest: no drift');
  process.exit(0);
}

console.log(`cockpit manifest: ${changes.length} change(s)`);
for (const c of changes) console.log(`  ${c}`);

if (CHECK) {
  console.log('\n--check: not written');
  process.exit(1);
}
writeFileSync(MANIFEST, JSON.stringify(manifest, null, 2) + '\n', 'utf8');
console.log('\nwritten.');
