#!/usr/bin/env node
// installer/render.mjs - generate every platform artefact from installer/manifest.mjs.
//
//   node installer/render.mjs           # (re)write installer/generated/**
//   node installer/render.mjs --check   # fail if generated output differs from the manifest
//   node installer/render.mjs --list    # print the configuration catalogue and exit
//
// The check is the same one contracts/tools/generate.mjs runs for the wire contract: the committed
// output is a function of one source, and drift is a build failure rather than a review comment.
// Nothing here writes a tenant, a token or a key - the generated files carry layout and
// placeholders only; the MDM-delivered profile carries the values.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CONFIG, LAYOUT, PRODUCT, configFor, expandDefault } from './manifest.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'installer', 'generated');
const ARGS = process.argv.slice(2);
const CHECK = ARGS.includes('--check');
const LIST = ARGS.includes('--list');
const ARGS_IDX = ARGS.indexOf('--args');

function valueOf(flag, fallback) {
  const i = ARGS.indexOf(flag);
  return i === -1 ? fallback : ARGS[i + 1];
}

/**
 * The argv-rendering mode. A config file is a set of per-tenant facts; this turns it into the exact
 * flag list capture-core resolves, so the Windows MSI, the macOS pkg and the Linux wrapper all
 * consume one mapping rather than three. Bools are `--flag=value` because Go's flag package does
 * not consume a separate token for them.
 */
if (ARGS_IDX !== -1) {
  const file = ARGS[ARGS_IDX + 1];
  if (!file) {
    console.error('render.mjs --args requires a config file path');
    process.exit(2);
  }
  const os = valueOf('--os', 'linux');
  if (!LAYOUT[os]) {
    console.error(`render.mjs --args: --os must be one of ${Object.keys(LAYOUT).join(', ')}`);
    process.exit(2);
  }
  const values = {};
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) values[m[1]] = m[2];
  }
  const parts = [];
  for (const c of configFor(os)) {
    const v = c.env in values ? values[c.env] : expandDefault(c, LAYOUT[os]);
    if (v === undefined || v === '') continue;
    if (c.kind === 'bool') parts.push(`${c.flag}=${v}`);
    else if (os === 'windows') parts.push(`${c.flag} "${v}"`);
    else parts.push(`${c.flag} "${v}"`);
  }
  process.stdout.write(parts.join(' ') + '\n');
  process.exit(0);
}

/**
 * The complete-profile mode. A profile may be a partial override (the lab one names the endpoint,
 * the CA and the token but not the install-layout paths). capture-core resolves only what the file
 * contains, so the installer must write a COMPLETE file: this merges the profile over the platform
 * defaults from the manifest and prints every key as KEY=VALUE.
 *
 *   node installer/render.mjs --env [FILE] --os windows
 */
const ENV_IDX = ARGS.indexOf('--env');
if (ENV_IDX !== -1) {
  const candidate = ARGS[ENV_IDX + 1];
  const file = candidate && !candidate.startsWith('--') ? candidate : '';
  const os = valueOf('--os', 'linux');
  if (!LAYOUT[os]) {
    console.error(`render.mjs --env: --os must be one of ${Object.keys(LAYOUT).join(', ')}`);
    process.exit(2);
  }
  const values = {};
  if (file) {
    for (const line of readFileSync(file, 'utf8').split('\n')) {
      const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
      if (m) values[m[1]] = m[2];
    }
  }
  const lines = [`# ${PRODUCT.displayName} enrolment profile (complete; profile merged over the ${os} defaults).`];
  for (const c of configFor(os)) {
    const v = c.env in values ? values[c.env] : expandDefault(c, LAYOUT[os]);
    lines.push(`${c.env}=${v}`);
  }
  process.stdout.write(lines.join('\n') + '\n');
  process.exit(0);
}

if (LIST) {
  for (const c of CONFIG) {
    const req = c.required ? ' required' : '';
    const sec = c.secret ? ' secret' : '';
    console.log(`${c.env.padEnd(26)} ${c.flag.padEnd(22)} ${c.kind}${req}${sec}`);
    console.log(`  ${c.desc}`);
  }
  process.exit(0);
}

const GENERATED_BY = 'generated by installer/render.mjs from installer/manifest.mjs - edit the manifest, not this file';

// ---------------------------------------------------------------------------------------------
// Helpers

/** A one-line comment a service manager will not confuse with content. */
function comment(text) {
  return `# ${text}`;
}

/**
 * The env file: every variable, grouped by the section comments in CONFIG order, with secrets left
 * empty. This is the file the customer's MDM replaces; the committed one is the template.
 */
function envExample() {
  const lines = [comment(GENERATED_BY), comment(`${PRODUCT.displayName} ${PRODUCT.version} - endpoint configuration template`), ''];
  lines.push(comment('This is a TEMPLATE. The customer\'s MDM writes the real values (the enrolment'));
  lines.push(comment('profile of docs/05-platform-delivery.md §6.2): the regional device FQDN, the'));
  lines.push(comment('credential mode, the pinned CA set, and a short-lived single-use enrolment token.'));
  lines.push(comment('The installer does not put tenant values in the artefact.'));
  lines.push('');
  const LinuxL = LAYOUT.linux;
  let section = '';
  for (const c of CONFIG) {
    if (c.section !== section) {
      section = c.section ?? '';
      if (section) lines.push('', comment(section));
    }
    lines.push(comment(c.desc));
    const value = c.secret ? '' : expandDefault(c, LinuxL);
    lines.push(`${c.env}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * The POSIX wrapper. It no longer maps the profile to flags itself: the agent reads the file with
 * --config-file, so the flag names live in one place (capture-core) instead of three, and a path or
 * secret with spaces needs no quoting.
 */
function shWrapper(layout) {
  return [
    '#!/bin/sh',
    comment(GENERATED_BY),
    comment('Exec capture-core with the enrolment profile (the agent reads it via --config-file).'),
    'set -eu',
    '',
    `CONFIG="\${SAC_CONFIG_FILE:-${layout.configFile}}"`,
    'if [ ! -f "$CONFIG" ]; then',
    '  echo "capture-core-run: configuration file $CONFIG not found" >&2',
    '  exit 1',
    'fi',
    '',
    `BIN="\${SAC_BINDIR:-${layout.bindir}}/capture-core"`,
    'if [ ! -x "$BIN" ]; then',
    '  echo "capture-core-run: $BIN is missing or not executable" >&2',
    '  exit 1',
    'fi',
    '',
    'exec "$BIN" --config-file "$CONFIG"',
    '',
  ].join('\n');
}

/** The Windows console helper, for a foreground run. The service uses the same file via --config-file. */
function cmdWrapper(layout) {
  return [
    '@echo off',
    'rem ' + GENERATED_BY,
    'rem Exec capture-core with the enrolment profile (the agent reads it via --config-file).',
    'setlocal enableextensions',
    `set "CONFIG=%SAC_CONFIG_FILE%"`,
    `if not defined CONFIG set "CONFIG=${layout.configFile}"`,
    'if not exist "%CONFIG%" (',
    '  echo capture-core-run: configuration file %CONFIG% not found 1>&2',
    '  exit /b 1',
    ')',
    `"${layout.bindir}\\capture-core.exe" --config-file "%CONFIG%"`,
    'exit /b %ERRORLEVEL%',
    '',
  ].join('\n');
}

/** The systemd unit. Restart-on-failure with a start limit, per cmd/capture-core/README.md §3.5. */
function systemdUnit(layout) {
  return [
    comment(GENERATED_BY),
    '[Unit]',
    `Description=${PRODUCT.displayName} endpoint agent`,
    'Documentation=file:/opt/shadow-ai-capture/README.txt',
    'After=network-online.target',
    'Wants=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `EnvironmentFile=${layout.configFile}`,
    `Environment=SAC_BINDIR=${layout.bindir}`,
    `ExecStart=${layout.bindir}/capture-core-run`,
    '# §3.5: no tight crash loop; a crash loop must stop and report absent, not restart forever.',
    'Restart=on-failure',
    'RestartSec=5',
    'StartLimitIntervalSec=60',
    'StartLimitBurst=5',
    '',
    '# The trust store and the system proxy are machine scope, so the service is root. The sandbox',
    '# keeps it to its own state and log directories.',
    'User=root',
    'NoNewPrivileges=true',
    'ProtectSystem=strict',
    'ProtectHome=true',
    'PrivateTmp=true',
    `ReadWritePaths=${layout.statedir} ${layout.logdir}`,
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

/** The LaunchDaemon. KeepAlive on non-zero exit only: a clean stop is not a restart signal. */
function launchdPlist(layout) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<!-- ' + GENERATED_BY + ' -->',
    '<plist version="1.0">',
    '<dict>',
    '  <key>Label</key>',
    `  <string>${layout.serviceName}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    `    <string>${layout.bindir}/capture-core-run</string>`,
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    '    <key>SAC_CONFIG_FILE</key>',
    `    <string>${layout.configFile}</string>`,
    '    <key>SAC_BINDIR</key>',
    `    <string>${layout.bindir}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    '  <dict>',
    '    <key>SuccessfulExit</key>',
    '    <false/>',
    '  </dict>',
    '  <key>StandardOutPath</key>',
    `  <string>${layout.logdir}/capture-core.out.log</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${layout.logdir}/capture-core.err.log</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

/**
 * The WiX v4 source. It installs the payload and registers capture-core as a LocalSystem service
 * whose Arguments are `--service --service-name ShadowAICapture` followed by the whole device argv
 * in the public property SAC_ARGS. capture-core implements the SCM contract itself in `--service`
 * mode (cmd/capture-core/service_windows.go), so no external wrapper (NSSM/WinSW) is needed; a
 * console program registered directly would fail to start. It is NOT VERIFIED - there is no WiX and
 * no Windows on the host this was written on; Build-Msi.ps1 says so and refuses to pretend.
 */
function wixSource(layout) {
  const component = (id, dir, sub, file) =>
    [
      `      <Component Id="Cmp_${id}" Directory="${dir}" Guid="*">`,
      `        <File Id="Fil_${id}" Source="$(var.StageDir)\\${sub}\\${file}" KeyPath="yes" />`,
      '      </Component>',
    ].join('\n');
  const binComponents = [
    component('classifier_host', 'BINFOLDER', 'bin', 'classifier-host.exe'),
    component('capture_core_run', 'BINFOLDER', 'bin', 'capture-core-run.cmd'),
  ].join('\n');
  const configComponent = component('capture_core_config', 'CONFIGFOLDER', 'etc', 'capture-core.env');
  const componentRefs = ['Cmp_Service', 'Cmp_classifier_host', 'Cmp_capture_core_run', 'Cmp_capture_core_config']
    .map((id) => `      <ComponentRef Id="${id}" />`)
    .join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- ' + GENERATED_BY + ' -->',
    '<!--',
    '  Development MSI source (docs/05-platform-delivery.md section 6.1). It installs the binaries, the',
    '  console wrapper and the enrolment profile (capture-core.env). The Windows service runs',
    '  capture-core in service mode and reads that file through the config-file flag, so no command',
    '  line is built from the profile and a path or secret with spaces needs no quoting. (An XML',
    '  comment cannot contain a double hyphen; keep it out of comments here.)',
    '-->',
    '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">',
    `  <Package Name="${PRODUCT.displayName}" Manufacturer="${PRODUCT.manufacturer}"`,
    `           Version="${PRODUCT.version}" UpgradeCode="${PRODUCT.upgradeCode}"`,
    '           Scope="perMachine" Compressed="yes">',
    '    <MajorUpgrade DowngradeErrorMessage="A newer version of Shadow AI Capture is already installed." />',
    '    <MediaTemplate EmbedCab="yes" />',
    '',
    '    <Property Id="ARPNOMODIFY" Value="1" />',
    '    <Property Id="ARPNOREPAIR" Value="1" />',
    '',
    '    <StandardDirectory Id="ProgramFiles64Folder">',
    '      <Directory Id="INSTALLFOLDER" Name="ShadowAICapture">',
    '        <Directory Id="BINFOLDER" Name="bin" />',
    '      </Directory>',
    '    </StandardDirectory>',
    '    <StandardDirectory Id="CommonAppDataFolder">',
    '      <Directory Id="CONFIGFOLDER" Name="ShadowAICapture">',
    '        <Directory Id="STATEFOLDER" Name="state" />',
    '        <Directory Id="LOGFOLDER" Name="log" />',
    '      </Directory>',
    '    </StandardDirectory>',
    '',
    '    <DirectoryRef Id="BINFOLDER">',
    binComponents,
    `      <Component Id="Cmp_Service" Directory="BINFOLDER" Guid="*">`,
    '        <File Id="Fil_ServiceExe" Source="$(var.StageDir)\\bin\\capture-core.exe" KeyPath="yes" />',
    '        <ServiceInstall Id="SvcCaptureCore" Name="ShadowAICapture" DisplayName="Shadow AI Capture"',
    '                        Description="Observes AI submissions on this device and drains them to the tenant ingress."',
    '                        Type="ownProcess" Start="auto" ErrorControl="normal" Account="LocalSystem"',
    '                        Arguments="--service --service-name ShadowAICapture --config-file C:\\ProgramData\\ShadowAICapture\\capture-core.env" />',
    '        <!-- Register with Start="auto" (starts at boot) but do NOT start during install: a service',
    '             that fails to start would abort the whole install transaction and roll the files back,',
    '             leaving nothing to diagnose. Start it with: sc.exe start ShadowAICapture -->',
    '        <ServiceControl Id="SvcCaptureCoreControl" Name="ShadowAICapture" Stop="both" Remove="uninstall" Wait="yes" />',
    '      </Component>',
    '    </DirectoryRef>',
    '    <DirectoryRef Id="CONFIGFOLDER">',
    configComponent,
    '    </DirectoryRef>',
    '',
    '    <Feature Id="Main" Title="Shadow AI Capture" Level="1">',
    componentRefs,
    '    </Feature>',
    '  </Package>',
    '</Wix>',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------------------------
// Output table

const FILES = [
  { path: 'capture-core.env.example', mode: 0o644, render: envExample },
  { path: 'linux/capture-core-run', mode: 0o755, render: () => shWrapper(LAYOUT.linux) },
  { path: 'linux/shadow-ai-capture.service', mode: 0o644, render: () => systemdUnit(LAYOUT.linux) },
  { path: 'macos/capture-core-run', mode: 0o755, render: () => shWrapper(LAYOUT.darwin) },
  { path: 'macos/com.shadowaicapture.capture-core.plist', mode: 0o644, render: () => launchdPlist(LAYOUT.darwin) },
  { path: 'windows/ShadowAICapture.wxs', mode: 0o644, render: () => wixSource(LAYOUT.windows) },
  { path: 'windows/capture-core-run.cmd', mode: 0o644, render: () => cmdWrapper(LAYOUT.windows) },
];

let drifted = 0;
for (const f of FILES) {
  const abs = join(OUT, f.path);
  const content = f.render();
  const before = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (CHECK) {
    if (before !== content) {
      console.error(`DRIFT ${f.path}`);
      drifted++;
    } else {
      console.log(`ok    ${f.path}`);
    }
    continue;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, { mode: f.mode });
  console.log(`write ${f.path}`);
}

if (CHECK && drifted > 0) {
  console.error(`\ninstaller/render.mjs --check: ${drifted} generated file(s) differ from installer/manifest.mjs.`);
  console.error('Run: node installer/render.mjs');
  process.exit(1);
}
if (CHECK) console.log('\ninstaller: generated output matches the manifest.');
