#!/usr/bin/env node
// installer/render.mjs - generate every platform artefact from installer/manifest.mjs.
//
//   node installer/render.mjs           # (re)write installer/generated/**
//   node installer/render.mjs --check   # fail if generated output differs from the manifest
//   node installer/render.mjs --list    # print the configuration catalogue and exit
//
// The check is the same one contracts/tools/generate.mjs runs for the wire contract: the committed
// output is a function of one source, and drift is a build failure rather than a review comment.
// Nothing here writes a tenant, a token or a key - the generated files carry layout and
// placeholders only; the MDM-delivered profile carries the values.

import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { CONFIG, LAYOUT, PAYLOAD, PRODUCT, configFor, expandDefault } from './manifest.mjs';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'installer', 'generated');
const ARGS = process.argv.slice(2);
const CHECK = ARGS.includes('--check');
const LIST = ARGS.includes('--list');
const ARGS_IDX = ARGS.indexOf('--args');

function valueOf(flag, fallback) {
  const i = ARGS.indexOf(flag);
  return i === -1 ? fallback : ARGS[i + 1];
}

/**
 * The argv-rendering mode. A config file is a set of per-tenant facts; this turns it into the exact
 * flag list capture-core resolves, so the Windows MSI, the macOS pkg and the Linux wrapper all
 * consume one mapping rather than three. Bools are `--flag=value` because Go's flag package does
 * not consume a separate token for them.
 */
if (ARGS_IDX !== -1) {
  const file = ARGS[ARGS_IDX + 1];
  if (!file) {
    console.error('render.mjs --args requires a config file path');
    process.exit(2);
  }
  const os = valueOf('--os', 'linux');
  if (!LAYOUT[os]) {
    console.error(`render.mjs --args: --os must be one of ${Object.keys(LAYOUT).join(', ')}`);
    process.exit(2);
  }
  const values = {};
  for (const line of readFileSync(file, 'utf8').split('\n')) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m) values[m[1]] = m[2];
  }
  const parts = [];
  for (const c of configFor(os)) {
    const v = c.env in values ? values[c.env] : expandDefault(c, LAYOUT[os]);
    if (v === undefined || v === '') continue;
    if (c.kind === 'bool') parts.push(`${c.flag}=${v}`);
    else if (os === 'windows') parts.push(`${c.flag} "${v}"`);
    else parts.push(`${c.flag} "${v}"`);
  }
  process.stdout.write(parts.join(' ') + '\n');
  process.exit(0);
}

if (LIST) {
  for (const c of CONFIG) {
    const req = c.required ? ' required' : '';
    const sec = c.secret ? ' secret' : '';
    console.log(`${c.env.padEnd(26)} ${c.flag.padEnd(22)} ${c.kind}${req}${sec}`);
    console.log(`  ${c.desc}`);
  }
  process.exit(0);
}

const GENERATED_BY = 'generated by installer/render.mjs from installer/manifest.mjs - edit the manifest, not this file';

// ---------------------------------------------------------------------------------------------
// Helpers

/** A one-line comment a service manager will not confuse with content. */
function comment(text) {
  return `# ${text}`;
}

/**
 * The env file: every variable, grouped by the section comments in CONFIG order, with secrets left
 * empty. This is the file the customer's MDM replaces; the committed one is the template.
 */
function envExample() {
  const lines = [comment(GENERATED_BY), comment(`${PRODUCT.displayName} ${PRODUCT.version} - endpoint configuration template`), ''];
  lines.push(comment('This is a TEMPLATE. The customer\'s MDM writes the real values (the enrolment'));
  lines.push(comment('profile of docs/05-platform-delivery.md §6.2): the regional device FQDN, the'));
  lines.push(comment('credential mode, the pinned CA set, and a short-lived single-use enrolment token.'));
  lines.push(comment('The installer does not put tenant values in the artefact.'));
  lines.push('');
  const LinuxL = LAYOUT.linux;
  let section = '';
  for (const c of CONFIG) {
    if (c.section !== section) {
      section = c.section ?? '';
      if (section) lines.push('', comment(section));
    }
    lines.push(comment(c.desc));
    const value = c.secret ? '' : expandDefault(c, LinuxL);
    lines.push(`${c.env}=${value}`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * The POSIX wrapper. capture-core resolves flags and nothing else, so the config file must become
 * argv. Go bool flags must be `--flag=value` (the flag package does not consume a separate token),
 * which is the one line worth getting right on all three platforms.
 */
function shWrapper(layout) {
  const lines = [
    '#!/bin/sh',
    comment(GENERATED_BY),
    comment('Source the enrolment profile and exec capture-core with the flags it resolves.'),
    'set -eu',
    '',
    `CONFIG="\${SAC_CONFIG_FILE:-${layout.configFile}}"`,
    'if [ ! -f "$CONFIG" ]; then',
    '  echo "capture-core-run: configuration file $CONFIG not found" >&2',
    '  exit 1',
    'fi',
    '# shellcheck source=/dev/null',
    '. "$CONFIG"',
    '',
    `BIN="\${SAC_BINDIR:-${layout.bindir}}/capture-core"`,
    'if [ ! -x "$BIN" ]; then',
    '  echo "capture-core-run: $BIN is missing or not executable" >&2',
    '  exit 1',
    'fi',
    '',
    'set --',
  ];
  for (const c of configFor('linux')) {
    if (c.kind === 'bool') {
      lines.push(`[ -n "\${${c.env}:-}" ] && set -- "$@" "${c.flag}=\${${c.env}}"`);
    } else {
      lines.push(`[ -n "\${${c.env}:-}" ] && set -- "$@" ${c.flag} "\${${c.env}}"`);
    }
  }
  lines.push('', 'exec "$BIN" "$@"', '');
  return lines.join('\n');
}

/** The Windows console helper, for a foreground run while developing. The service uses SAC_ARGS. */
function cmdWrapper(layout) {
  const lines = [
    '@echo off',
    'rem ' + GENERATED_BY,
    'rem Source the enrolment profile and exec capture-core with the flags it resolves.',
    'setlocal enableextensions enabledelayedexpansion',
    `set "CONFIG=%SAC_CONFIG_FILE%"`,
    `if not defined CONFIG set "CONFIG=${layout.configFile}"`,
    'if not exist "%CONFIG%" (',
    '  echo capture-core-run: configuration file %CONFIG% not found 1>&2',
    '  exit /b 1',
    ')',
    'for /f "usebackq tokens=1,* delims==" %%A in (`findstr /b /v "#" "%CONFIG%"`) do set "%%A=%%B"',
    'set "ARGS="',
  ];
  for (const c of configFor('windows')) {
    if (c.kind === 'bool') {
      lines.push(`if defined ${c.env} set "ARGS=!ARGS! ${c.flag}=!${c.env}!"`);
    } else {
      lines.push(`if defined ${c.env} set "ARGS=!ARGS! ${c.flag} "!${c.env}!""`);
    }
  }
  lines.push(`"${layout.bindir}\\capture-core.exe" %ARGS%`, 'exit /b %ERRORLEVEL%', '');
  return lines.join('\n');
}

/** The systemd unit. Restart-on-failure with a start limit, per cmd/capture-core/README.md §3.5. */
function systemdUnit(layout) {
  return [
    comment(GENERATED_BY),
    '[Unit]',
    `Description=${PRODUCT.displayName} endpoint agent`,
    'Documentation=file:/opt/shadow-ai-capture/README.txt',
    'After=network-online.target',
    'Wants=network-online.target',
    '',
    '[Service]',
    'Type=simple',
    `EnvironmentFile=${layout.configFile}`,
    `Environment=SAC_BINDIR=${layout.bindir}`,
    `ExecStart=${layout.bindir}/capture-core-run`,
    '# §3.5: no tight crash loop; a crash loop must stop and report absent, not restart forever.',
    'Restart=on-failure',
    'RestartSec=5',
    'StartLimitIntervalSec=60',
    'StartLimitBurst=5',
    '',
    '# The trust store and the system proxy are machine scope, so the service is root. The sandbox',
    '# keeps it to its own state and log directories.',
    'User=root',
    'NoNewPrivileges=true',
    'ProtectSystem=strict',
    'ProtectHome=true',
    'PrivateTmp=true',
    `ReadWritePaths=${layout.statedir} ${layout.logdir}`,
    '',
    '[Install]',
    'WantedBy=multi-user.target',
    '',
  ].join('\n');
}

/** The LaunchDaemon. KeepAlive on non-zero exit only: a clean stop is not a restart signal. */
function launchdPlist(layout) {
  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
    '<!-- ' + GENERATED_BY + ' -->',
    '<plist version="1.0">',
    '<dict>',
    '  <key>Label</key>',
    `  <string>${layout.serviceName}</string>`,
    '  <key>ProgramArguments</key>',
    '  <array>',
    `    <string>${layout.bindir}/capture-core-run</string>`,
    '  </array>',
    '  <key>EnvironmentVariables</key>',
    '  <dict>',
    '    <key>SAC_CONFIG_FILE</key>',
    `    <string>${layout.configFile}</string>`,
    '    <key>SAC_BINDIR</key>',
    `    <string>${layout.bindir}</string>`,
    '  </dict>',
    '  <key>RunAtLoad</key>',
    '  <true/>',
    '  <key>KeepAlive</key>',
    '  <dict>',
    '    <key>SuccessfulExit</key>',
    '    <false/>',
    '  </dict>',
    '  <key>StandardOutPath</key>',
    `  <string>${layout.logdir}/capture-core.out.log</string>`,
    '  <key>StandardErrorPath</key>',
    `  <string>${layout.logdir}/capture-core.err.log</string>`,
    '</dict>',
    '</plist>',
    '',
  ].join('\n');
}

/**
 * The WiX v4 source. It installs the payload and registers capture-core as a LocalSystem service
 * whose Arguments are `--service --service-name ShadowAICapture` followed by the whole device argv
 * in the public property SAC_ARGS. capture-core implements the SCM contract itself in `--service`
 * mode (cmd/capture-core/service_windows.go), so no external wrapper (NSSM/WinSW) is needed; a
 * console program registered directly would fail to start. It is NOT VERIFIED - there is no WiX and
 * no Windows on the host this was written on; Build-Msi.ps1 says so and refuses to pretend.
 */
function wixSource(layout) {
  // capture-core.exe is installed by the service component below: a ServiceInstall must live in a
  // component whose KeyPath is the executable, so including it in the payload loop as well would
  // install the same file twice (and, because the payload loop targeted INSTALLFOLDER while the
  // service targets BINFOLDER, in two places).
  const payloadComponents = PAYLOAD.filter((p) => p.name !== 'capture-core');
  // The stage filename is platform-specific: executables get `.exe`, the console wrapper is `.cmd`,
  // and the env template keeps its name. `bin`/`etc` is the stage subdirectory the file lives in.
  const stageName = (p) => (p.name === 'capture-core-run' ? 'capture-core-run.cmd' : p.exe ? `${p.name}.exe` : p.name);
  const stageDir = (p) => (p.dest === 'etc' ? 'etc' : 'bin');
  const render = payloadComponents.map((p) => {
    const dir = p.dest === 'etc' ? 'CONFIGFOLDER' : 'BINFOLDER';
    return [
      `      <Component Id="Cmp_${p.name.replace(/[^A-Za-z0-9]/g, '_')}" Directory="${dir}" Guid="*">`,
      `        <File Id="Fil_${p.name.replace(/[^A-Za-z0-9]/g, '_')}" Source="$(var.StageDir)\\${stageDir(p)}\\${stageName(p)}" KeyPath="yes" />`,
      '      </Component>',
    ].join('\n');
  }).join('\n');

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- ' + GENERATED_BY + ' -->',
    '<!--',
    '  Development MSI source (docs/05-platform-delivery.md §6.1). It carries code only; the',
    '  per-tenant enrolment profile is delivered by the customer MDM. The service argv is the public',
    '  property SAC_ARGS; pass it on the msiexec command line, or let Build-Msi.ps1 compose it from a',
    '  config file. (An XML comment cannot contain a double hyphen, so the example argv lives in',
    '  installer/README.md instead of here.)',
    '-->',
    '<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">',
    `  <Package Name="${PRODUCT.displayName}" Manufacturer="${PRODUCT.manufacturer}"`,
    `           Version="${PRODUCT.version}" UpgradeCode="${PRODUCT.upgradeCode}"`,
    '           Scope="perMachine" Compressed="yes">',
    '    <MajorUpgrade DowngradeErrorMessage="A newer version of Shadow AI Capture is already installed." />',
    '    <MediaTemplate EmbedCab="yes" />',
    '',
    '    <Property Id="ARPNOMODIFY" Value="1" />',
    '    <Property Id="ARPNOREPAIR" Value="1" />',
    '    <!-- The whole device argv, composed from a config file by Build-Msi.ps1 and overridable at install. -->',
    '    <Property Id="SAC_ARGS" Value="$(var.SacArgs)" Secure="yes" />',
    '',
    '    <StandardDirectory Id="ProgramFiles64Folder">',
    '      <Directory Id="INSTALLFOLDER" Name="ShadowAICapture">',
    '        <Directory Id="BINFOLDER" Name="bin" />',
    '      </Directory>',
    '    </StandardDirectory>',
    '    <StandardDirectory Id="CommonAppDataFolder">',
    '      <Directory Id="CONFIGFOLDER" Name="ShadowAICapture">',
    '        <Directory Id="STATEFOLDER" Name="state" />',
    '        <Directory Id="LOGFOLDER" Name="log" />',
    '      </Directory>',
    '    </StandardDirectory>',
    '',
    '    <DirectoryRef Id="BINFOLDER">',
    render,
    `      <Component Id="Cmp_Service" Directory="BINFOLDER" Guid="*">`,
    '        <File Id="Fil_ServiceExe" Source="$(var.StageDir)\\bin\\capture-core.exe" KeyPath="yes" />',
    '        <ServiceInstall Id="SvcCaptureCore" Name="ShadowAICapture" DisplayName="Shadow AI Capture"',
    '                        Description="Observes AI submissions on this device and drains them to the tenant ingress."',
    '                        Type="ownProcess" Start="auto" ErrorControl="normal" Account="LocalSystem"',
    '                        Arguments="--service --service-name ShadowAICapture [SAC_ARGS]" />',
    '        <!-- Register with Start="auto" (starts at boot) but do NOT start during install: a service',
    '             that fails to start would abort the whole install transaction and roll the files back,',
    '             leaving nothing to diagnose. Start it with: sc.exe start ShadowAICapture -->',
    '        <ServiceControl Id="SvcCaptureCoreControl" Name="ShadowAICapture" Stop="both" Remove="uninstall" Wait="yes" />',
    '      </Component>',
    '    </DirectoryRef>',
    '',
    '    <Feature Id="Main" Title="Shadow AI Capture" Level="1">',
    '      <ComponentRef Id="Cmp_Service" />',
    payloadComponents.map((p) => `      <ComponentRef Id="Cmp_${p.name.replace(/[^A-Za-z0-9]/g, '_')}" />`).join('\n'),
    '    </Feature>',
    '  </Package>',
    '</Wix>',
    '',
  ].join('\n');
}

// ---------------------------------------------------------------------------------------------
// Output table

const FILES = [
  { path: 'capture-core.env.example', mode: 0o644, render: envExample },
  { path: 'linux/capture-core-run', mode: 0o755, render: () => shWrapper(LAYOUT.linux) },
  { path: 'linux/shadow-ai-capture.service', mode: 0o644, render: () => systemdUnit(LAYOUT.linux) },
  { path: 'macos/capture-core-run', mode: 0o755, render: () => shWrapper(LAYOUT.darwin) },
  { path: 'macos/com.shadowaicapture.capture-core.plist', mode: 0o644, render: () => launchdPlist(LAYOUT.darwin) },
  { path: 'windows/ShadowAICapture.wxs', mode: 0o644, render: () => wixSource(LAYOUT.windows) },
  { path: 'windows/capture-core-run.cmd', mode: 0o644, render: () => cmdWrapper(LAYOUT.windows) },
];

let drifted = 0;
for (const f of FILES) {
  const abs = join(OUT, f.path);
  const content = f.render();
  const before = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (CHECK) {
    if (before !== content) {
      console.error(`DRIFT ${f.path}`);
      drifted++;
    } else {
      console.log(`ok    ${f.path}`);
    }
    continue;
  }
  mkdirSync(dirname(abs), { recursive: true });
  writeFileSync(abs, content, { mode: f.mode });
  console.log(`write ${f.path}`);
}

if (CHECK && drifted > 0) {
  console.error(`\ninstaller/render.mjs --check: ${drifted} generated file(s) differ from installer/manifest.mjs.`);
  console.error('Run: node installer/render.mjs');
  process.exit(1);
}
if (CHECK) console.log('\ninstaller: generated output matches the manifest.');
